// elementaltakedown/src/main/webapp/app/entities/basic-atk/detail/basic-atk-detail.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute } from '@angular/router';

import { IBasicATK } from '../basic-atk.model';

@Component({
  selector: 'jhi-basic-atk-detail',
  templateUrl: './basic-atk-detail.component.html',
})
export class BasicATKDetailComponent implements OnInit {
  basicATK: IBasicATK | null = null;

  constructor(protected activatedRoute: ActivatedRoute) {}

  ngOnInit(): void {
    this.activatedRoute.data.subscribe(({ basicATK }) => {
      this.basicATK = basicATK;
    });
  }

  previousState(): void {
    window.history.back();
  }
}

<div class="d-flex justify-content-center">
  <div class="col-8">
    <div *ngIf="basicATK">
      <h2 data-cy="basicATKDetailsHeading"><span jhiTranslate="elementaltakedownApp.basicATK.detail.title">Basic ATK</span></h2>

      <hr />

      <jhi-alert-error></jhi-alert-error>

      <jhi-alert></jhi-alert>

      <dl class="row-md jh-entity-details">
        <dt><span jhiTranslate="global.field.id">ID</span></dt>
        <dd>
          <span>{{ basicATK.id }}</span>
        </dd>
        <dt><span jhiTranslate="elementaltakedownApp.basicATK.name">Name</span></dt>
        <dd>
          <span>{{ basicATK.name }}</span>
        </dd>
        <dt><span jhiTranslate="elementaltakedownApp.basicATK.description">Description</span></dt>
        <dd>
          <span>{{ basicATK.description }}</span>
        </dd>
        <dt><span jhiTranslate="elementaltakedownApp.basicATK.damage">Damage</span></dt>
        <dd>
          <div *ngIf="basicATK.damage">
            <a [routerLink]="['/damage', basicATK.damage.id, 'view']">{{ basicATK.damage.name }}</a>
          </div>
        </dd>
      </dl>

      <button type="submit" (click)="previousState()" class="btn btn-info" data-cy="entityDetailsBackButton">
        <fa-icon icon="arrow-left"></fa-icon>&nbsp;<span jhiTranslate="entity.action.back">Back</span>
      </button>

      <button type="button" [routerLink]="['/basic-atk', basicATK.id, 'edit']" class="btn btn-primary">
        <fa-icon icon="pencil-alt"></fa-icon>&nbsp;<span jhiTranslate="entity.action.edit">Edit</span>
      </button>
    </div>
  </div>
</div>

// elementaltakedown/src/main/webapp/app/entities/basic-atk/basic-atk-detail.tsx
import React, { useEffect } from 'react';
import { Link, useParams } from 'react-router-dom';
import { Button, Row, Col } from 'reactstrap';
import { Translate } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { APP_DATE_FORMAT, APP_LOCAL_DATE_FORMAT } from 'app/config/constants';
import { useAppDispatch, useAppSelector } from 'app/config/store';

import { getEntity } from './basic-atk.reducer';

export const BasicATKDetail = () => {
  const dispatch = useAppDispatch();

  const { id } = useParams<'id'>();

  useEffect(() => {
    dispatch(getEntity(id));
  }, []);

  const basicATKEntity = useAppSelector(state => state.basicATK.entity);
  return (
    <Row>
      <Col md="8">
        <h2 data-cy="basicATKDetailsHeading">
          <Translate contentKey="elementaltakedownApp.basicATK.detail.title">BasicATK</Translate>
        </h2>
        <dl className="jh-entity-details">
          <dt>
            <span id="id">
              <Translate contentKey="global.field.id">ID</Translate>
            </span>
          </dt>
          <dd>{basicATKEntity.id}</dd>
          <dt>
            <span id="name">
              <Translate contentKey="elementaltakedownApp.basicATK.name">Name</Translate>
            </span>
          </dt>
          <dd>{basicATKEntity.name}</dd>
          <dt>
            <span id="description">
              <Translate contentKey="elementaltakedownApp.basicATK.description">Description</Translate>
            </span>
          </dt>
          <dd>{basicATKEntity.description}</dd>
          <dt>
            <Translate contentKey="elementaltakedownApp.basicATK.damage">Damage</Translate>
          </dt>
          <dd>{basicATKEntity.damage ? basicATKEntity.damage.name : ''}</dd>
        </dl>
        <Button tag={Link} to="/basic-atk" replace color="info" data-cy="entityDetailsBackButton">
          <FontAwesomeIcon icon="arrow-left" />{' '}
          <span className="d-none d-md-inline">
            <Translate contentKey="entity.action.back">Back</Translate>
          </span>
        </Button>
        &nbsp;
        <Button tag={Link} to={`/basic-atk/${basicATKEntity.id}/edit`} replace color="primary">
          <FontAwesomeIcon icon="pencil-alt" />{' '}
          <span className="d-none d-md-inline">
            <Translate contentKey="entity.action.edit">Edit</Translate>
          </span>
        </Button>
      </Col>
    </Row>
  );
};

export default BasicATKDetail;
