// elementaltakedown/src/main/webapp/app/entities/basic-atk/update/basic-atk-update.component.ts
import { Component, OnInit } from '@angular/core';
import { HttpResponse } from '@angular/common/http';
import { ActivatedRoute } from '@angular/router';
import { Observable } from 'rxjs';
import { finalize, map } from 'rxjs/operators';

import { BasicATKFormService, BasicATKFormGroup } from './basic-atk-form.service';
import { IBasicATK } from '../basic-atk.model';
import { BasicATKService } from '../service/basic-atk.service';
import { IDamage } from 'app/entities/damage/damage.model';
import { DamageService } from 'app/entities/damage/service/damage.service';

@Component({
  selector: 'jhi-basic-atk-update',
  templateUrl: './basic-atk-update.component.html',
})
export class BasicATKUpdateComponent implements OnInit {
  isSaving = false;
  basicATK: IBasicATK | null = null;

  damagesSharedCollection: IDamage[] = [];

  editForm: BasicATKFormGroup = this.basicATKFormService.createBasicATKFormGroup();

  constructor(
    protected basicATKService: BasicATKService,
    protected basicATKFormService: BasicATKFormService,
    protected damageService: DamageService,
    protected activatedRoute: ActivatedRoute
  ) {}

  compareDamage = (o1: IDamage | null, o2: IDamage | null): boolean => this.damageService.compareDamage(o1, o2);

  ngOnInit(): void {
    this.activatedRoute.data.subscribe(({ basicATK }) => {
      this.basicATK = basicATK;
      if (basicATK) {
        this.updateForm(basicATK);
      }

      this.loadRelationshipsOptions();
    });
  }

  previousState(): void {
    window.history.back();
  }

  save(): void {
    this.isSaving = true;
    const basicATK = this.basicATKFormService.getBasicATK(this.editForm);
    if (basicATK.id !== null) {
      this.subscribeToSaveResponse(this.basicATKService.update(basicATK));
    } else {
      this.subscribeToSaveResponse(this.basicATKService.create(basicATK));
    }
  }

  protected subscribeToSaveResponse(result: Observable<HttpResponse<IBasicATK>>): void {
    result.pipe(finalize(() => this.onSaveFinalize())).subscribe({
      next: () => this.onSaveSuccess(),
      error: () => this.onSaveError(),
    });
  }

  protected onSaveSuccess(): void {
    this.previousState();
  }

  protected onSaveError(): void {
    // Api for inheritance.
  }

  protected onSaveFinalize(): void {
    this.isSaving = false;
  }

  protected updateForm(basicATK: IBasicATK): void {
    this.basicATK = basicATK;
    this.basicATKFormService.resetForm(this.editForm, basicATK);

    this.damagesSharedCollection = this.damageService.addDamageToCollectionIfMissing<IDamage>(
      this.damagesSharedCollection,
      basicATK.damage
    );
  }

  protected loadRelationshipsOptions(): void {
    this.damageService
      .query()
      .pipe(map((res: HttpResponse<IDamage[]>) => res.body ?? []))
      .pipe(map((damages: IDamage[]) => this.damageService.addDamageToCollectionIfMissing<IDamage>(damages, this.basicATK?.damage)))
      .subscribe((damages: IDamage[]) => (this.damagesSharedCollection = damages));
  }
}

<div class="d-flex justify-content-center">
  <div class="col-8">
    <form name="editForm" role="form" novalidate (ngSubmit)="save()" [formGroup]="editForm">
      <h2
        id="jhi-basic-atk-heading"
        data-cy="BasicATKCreateUpdateHeading"
        jhiTranslate="elementaltakedownApp.basicATK.home.createOrEditLabel"
      >
        Create or edit a Basic ATK
      </h2>

      <div>
        <jhi-alert-error></jhi-alert-error>

        <div class="row mb-3" *ngIf="editForm.controls.id.value !== null">
          <label class="form-label" jhiTranslate="global.field.id" for="field_id">ID</label>
          <input type="number" class="form-control" name="id" id="field_id" data-cy="id" formControlName="id" [readonly]="true" />
        </div>

        <div class="row mb-3">
          <label class="form-label" jhiTranslate="elementaltakedownApp.basicATK.name" for="field_name">Name</label>
          <input type="text" class="form-control" name="name" id="field_name" data-cy="name" formControlName="name" />
        </div>

        <div class="row mb-3">
          <label class="form-label" jhiTranslate="elementaltakedownApp.basicATK.description" for="field_description">Description</label>
          <input
            type="text"
            class="form-control"
            name="description"
            id="field_description"
            data-cy="description"
            formControlName="description"
          />
        </div>

        <div class="row mb-3">
          <label class="form-label" jhiTranslate="elementaltakedownApp.basicATK.damage" for="field_damage">Damage</label>
          <select
            class="form-control"
            id="field_damage"
            data-cy="damage"
            name="damage"
            formControlName="damage"
            [compareWith]="compareDamage"
          >
            <option *ngIf="!editForm.get('damage')!.value" [ngValue]="null" selected></option>
            <option [ngValue]="damageOption" *ngFor="let damageOption of damagesSharedCollection">{{ damageOption.name }}</option>
          </select>
        </div>
        <div *ngIf="editForm.get(['damage'])!.invalid && (editForm.get(['damage'])!.dirty || editForm.get(['damage'])!.touched)">
          <small class="form-text text-danger" *ngIf="editForm.get(['damage'])?.errors?.required" jhiTranslate="entity.validation.required">
            This field is required.
          </small>
        </div>
      </div>

      <div>
        <button type="button" id="cancel-save" data-cy="entityCreateCancelButton" class="btn btn-secondary" (click)="previousState()">
          <fa-icon icon="ban"></fa-icon>&nbsp;<span jhiTranslate="entity.action.cancel">Cancel</span>
        </button>

        <button
          type="submit"
          id="save-entity"
          data-cy="entityCreateSaveButton"
          [disabled]="editForm.invalid || isSaving"
          class="btn btn-primary"
        >
          <fa-icon icon="save"></fa-icon>&nbsp;<span jhiTranslate="entity.action.save">Save</span>
        </button>
      </div>
    </form>
  </div>
</div>

// elementaltakedown/src/main/webapp/app/entities/basic-atk/basic-atk-update.tsx
import React, { useState, useEffect } from 'react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import { Button, Row, Col, FormText } from 'reactstrap';
import { isNumber, Translate, translate, ValidatedField, ValidatedForm } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { convertDateTimeFromServer, convertDateTimeToServer, displayDefaultDateTime } from 'app/shared/util/date-utils';
import { mapIdList } from 'app/shared/util/entity-utils';
import { useAppDispatch, useAppSelector } from 'app/config/store';

import { IDamage } from 'app/shared/model/damage.model';
import { getEntities as getDamages } from 'app/entities/damage/damage.reducer';
import { IBasicATK } from 'app/shared/model/basic-atk.model';
import { getEntity, updateEntity, createEntity, reset } from './basic-atk.reducer';

export const BasicATKUpdate = () => {
  const dispatch = useAppDispatch();

  const navigate = useNavigate();

  const { id } = useParams<'id'>();
  const isNew = id === undefined;

  const damages = useAppSelector(state => state.damage.entities);
  const basicATKEntity = useAppSelector(state => state.basicATK.entity);
  const loading = useAppSelector(state => state.basicATK.loading);
  const updating = useAppSelector(state => state.basicATK.updating);
  const updateSuccess = useAppSelector(state => state.basicATK.updateSuccess);

  const handleClose = () => {
    navigate('/basic-atk');
  };

  useEffect(() => {
    if (isNew) {
      dispatch(reset());
    } else {
      dispatch(getEntity(id));
    }

    dispatch(getDamages({}));
  }, []);

  useEffect(() => {
    if (updateSuccess) {
      handleClose();
    }
  }, [updateSuccess]);

  const saveEntity = values => {
    const entity = {
      ...basicATKEntity,
      ...values,
      damage: damages.find(it => it.id.toString() === values.damage.toString()),
    };

    if (isNew) {
      dispatch(createEntity(entity));
    } else {
      dispatch(updateEntity(entity));
    }
  };

  const defaultValues = () =>
    isNew
      ? {}
      : {
          ...basicATKEntity,
          damage: basicATKEntity?.damage?.id,
        };

  return (
    <div>
      <Row className="justify-content-center">
        <Col md="8">
          <h2 id="elementaltakedownApp.basicATK.home.createOrEditLabel" data-cy="BasicATKCreateUpdateHeading">
            <Translate contentKey="elementaltakedownApp.basicATK.home.createOrEditLabel">Create or edit a BasicATK</Translate>
          </h2>
        </Col>
      </Row>
      <Row className="justify-content-center">
        <Col md="8">
          {loading ? (
            <p>Loading...</p>
          ) : (
            <ValidatedForm defaultValues={defaultValues()} onSubmit={saveEntity}>
              {!isNew ? (
                <ValidatedField
                  name="id"
                  required
                  readOnly
                  id="basic-atk-id"
                  label={translate('global.field.id')}
                  validate={{ required: true }}
                />
              ) : null}
              <ValidatedField
                label={translate('elementaltakedownApp.basicATK.name')}
                id="basic-atk-name"
                name="name"
                data-cy="name"
                type="text"
              />
              <ValidatedField
                label={translate('elementaltakedownApp.basicATK.description')}
                id="basic-atk-description"
                name="description"
                data-cy="description"
                type="text"
              />
              <ValidatedField
                id="basic-atk-damage"
                name="damage"
                data-cy="damage"
                label={translate('elementaltakedownApp.basicATK.damage')}
                type="select"
                required
              >
                <option value="" key="0" />
                {damages
                  ? damages.map(otherEntity => (
                      <option value={otherEntity.id} key={otherEntity.id}>
                        {otherEntity.name}
                      </option>
                    ))
                  : null}
              </ValidatedField>
              <FormText>
                <Translate contentKey="entity.validation.required">This field is required.</Translate>
              </FormText>
              <Button tag={Link} id="cancel-save" data-cy="entityCreateCancelButton" to="/basic-atk" replace color="info">
                <FontAwesomeIcon icon="arrow-left" />
                &nbsp;
                <span className="d-none d-md-inline">
                  <Translate contentKey="entity.action.back">Back</Translate>
                </span>
              </Button>
              &nbsp;
              <Button color="primary" id="save-entity" data-cy="entityCreateSaveButton" type="submit" disabled={updating}>
                <FontAwesomeIcon icon="save" />
                &nbsp;
                <Translate contentKey="entity.action.save">Save</Translate>
              </Button>
            </ValidatedForm>
          )}
        </Col>
      </Row>
    </div>
  );
};

export default BasicATKUpdate;
