// elementaltakedown/src/main/webapp/app/entities/character-card/character-card.tsx
import React, { useState, useEffect } from 'react';
import { Link, useLocation, useNavigate } from 'react-router-dom';
import { Button, Table } from 'reactstrap';
import { Translate } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { APP_DATE_FORMAT, APP_LOCAL_DATE_FORMAT } from 'app/config/constants';
import { useAppDispatch, useAppSelector } from 'app/config/store';

import { ICharacterCard } from 'app/shared/model/character-card.model';
import { getEntities } from './character-card.reducer';

export const CharacterCard = () => {
  const dispatch = useAppDispatch();

  const location = useLocation();
  const navigate = useNavigate();

  const characterCardList = useAppSelector(state => state.characterCard.entities);
  const loading = useAppSelector(state => state.characterCard.loading);

  useEffect(() => {
    dispatch(getEntities({}));
  }, []);

  const handleSyncList = () => {
    dispatch(getEntities({}));
  };

  return (
    <div>
      <h2 id="character-card-heading" data-cy="CharacterCardHeading">
        <Translate contentKey="elementaltakedownApp.characterCard.home.title">Character Cards</Translate>
        <div className="d-flex justify-content-end">
          <Button className="me-2" color="info" onClick={handleSyncList} disabled={loading}>
            <FontAwesomeIcon icon="sync" spin={loading} />{' '}
            <Translate contentKey="elementaltakedownApp.characterCard.home.refreshListLabel">Refresh List</Translate>
          </Button>
          <Link to="/character-card/new" className="btn btn-primary jh-create-entity" id="jh-create-entity" data-cy="entityCreateButton">
            <FontAwesomeIcon icon="plus" />
            &nbsp;
            <Translate contentKey="elementaltakedownApp.characterCard.home.createLabel">Create new Character Card</Translate>
          </Link>
        </div>
      </h2>
      <div className="table-responsive">
        {characterCardList && characterCardList.length > 0 ? (
          <Table responsive>
            <thead>
              <tr>
                <th>
                  <Translate contentKey="elementaltakedownApp.characterCard.id">ID</Translate>
                </th>
                <th>
                  <Translate contentKey="elementaltakedownApp.characterCard.name">Name</Translate>
                </th>
                <th>
                  <Translate contentKey="elementaltakedownApp.characterCard.element">Element</Translate>
                </th>
                <th>
                  <Translate contentKey="elementaltakedownApp.characterCard.basic">Basic</Translate>
                </th>
                <th>
                  <Translate contentKey="elementaltakedownApp.characterCard.skill">Skill</Translate>
                </th>
                <th>
                  <Translate contentKey="elementaltakedownApp.characterCard.ultimate">Ultimate</Translate>
                </th>
                <th />
              </tr>
            </thead>
            <tbody>
              {characterCardList.map((characterCard, i) => (
                <tr key={`entity-${i}`} data-cy="entityTable">
                  <td>
                    <Button tag={Link} to={`/character-card/${characterCard.id}`} color="link" size="sm">
                      {characterCard.id}
                    </Button>
                  </td>
                  <td>{characterCard.name}</td>
                  <td>
                    <Translate contentKey={`elementaltakedownApp.ElementType.${characterCard.element}`} />
                  </td>
                  <td>{characterCard.basic ? <Link to={`/basic-atk/${characterCard.basic.id}`}>{characterCard.basic.name}</Link> : ''}</td>
                  <td>{characterCard.skill ? <Link to={`/skill-atk/${characterCard.skill.id}`}>{characterCard.skill.name}</Link> : ''}</td>
                  <td>
                    {characterCard.ultimate ? (
                      <Link to={`/ultimate-atk/${characterCard.ultimate.id}`}>{characterCard.ultimate.name}</Link>
                    ) : (
                      ''
                    )}
                  </td>
                  <td className="text-end">
                    <div className="btn-group flex-btn-group-container">
                      <Button tag={Link} to={`/character-card/${characterCard.id}`} color="info" size="sm" data-cy="entityDetailsButton">
                        <FontAwesomeIcon icon="eye" />{' '}
                        <span className="d-none d-md-inline">
                          <Translate contentKey="entity.action.view">View</Translate>
                        </span>
                      </Button>
                      <Button
                        tag={Link}
                        to={`/character-card/${characterCard.id}/edit`}
                        color="primary"
                        size="sm"
                        data-cy="entityEditButton"
                      >
                        <FontAwesomeIcon icon="pencil-alt" />{' '}
                        <span className="d-none d-md-inline">
                          <Translate contentKey="entity.action.edit">Edit</Translate>
                        </span>
                      </Button>
                      <Button
                        tag={Link}
                        to={`/character-card/${characterCard.id}/delete`}
                        color="danger"
                        size="sm"
                        data-cy="entityDeleteButton"
                      >
                        <FontAwesomeIcon icon="trash" />{' '}
                        <span className="d-none d-md-inline">
                          <Translate contentKey="entity.action.delete">Delete</Translate>
                        </span>
                      </Button>
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </Table>
        ) : (
          !loading && (
            <div className="alert alert-warning">
              <Translate contentKey="elementaltakedownApp.characterCard.home.notFound">No Character Cards found</Translate>
            </div>
          )
        )}
      </div>
    </div>
  );
};

export default CharacterCard;

// elementaltakedown/src/main/webapp/app/archive/list/character-card.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute, Data, ParamMap, Router } from '@angular/router';
import { combineLatest, filter, Observable, switchMap, tap } from 'rxjs';
import { NgbModal } from '@ng-bootstrap/ng-bootstrap';

import { ICharacterCard } from '../character-card.model';
import { ASC, DESC, SORT, ITEM_DELETED_EVENT, DEFAULT_SORT_DATA } from 'app/config/navigation.constants';
import { EntityArrayResponseType, CharacterCardService } from '../service/character-card.service';
import { CharacterCardDeleteDialogComponent } from '../delete/character-card-delete-dialog.component';
import { SortService } from 'app/shared/sort/sort.service';

import { AccountService } from 'app/core/auth/account.service';
import { Account } from 'app/core/auth/account.model';

@Component({
  selector: 'jhi-character-card',
  templateUrl: './character-card.component.html',
})
export class CharacterCardComponent implements OnInit {
  characterCards?: ICharacterCard[];
  isLoading = false;
  account: Account | null = null;

  predicate = 'id';
  ascending = true;

  constructor(
    protected characterCardService: CharacterCardService,
    protected activatedRoute: ActivatedRoute,
    public router: Router,
    protected sortService: SortService,
    private accountService: AccountService,
    protected modalService: NgbModal
  ) {}

  trackId = (_index: number, item: ICharacterCard): number => this.characterCardService.getCharacterCardIdentifier(item);

  ngOnInit(): void {
    this.load();
    this.accountService.getAuthenticationState().subscribe(account => (this.account = account));
//     console.log(this.account);
  }

  delete(characterCard: ICharacterCard): void {
    const modalRef = this.modalService.open(CharacterCardDeleteDialogComponent, { size: 'lg', backdrop: 'static' });
    modalRef.componentInstance.characterCard = characterCard;
    // unsubscribe not needed because closed completes on modal close
    modalRef.closed
      .pipe(
        filter(reason => reason === ITEM_DELETED_EVENT),
        switchMap(() => this.loadFromBackendWithRouteInformations())
      )
      .subscribe({
        next: (res: EntityArrayResponseType) => {
          this.onResponseSuccess(res);
        },
      });
  }

  load(): void {
    this.loadFromBackendWithRouteInformations().subscribe({
      next: (res: EntityArrayResponseType) => {
        this.onResponseSuccess(res);
      },
    });
  }

  navigateToWithComponentValues(): void {
    this.handleNavigation(this.predicate, this.ascending);
  }

  protected loadFromBackendWithRouteInformations(): Observable<EntityArrayResponseType> {
    return combineLatest([this.activatedRoute.queryParamMap, this.activatedRoute.data]).pipe(
      tap(([params, data]) => this.fillComponentAttributeFromRoute(params, data)),
      switchMap(() => this.queryBackend(this.predicate, this.ascending))
    );
  }

  protected fillComponentAttributeFromRoute(params: ParamMap, data: Data): void {
    const sort = (params.get(SORT) ?? data[DEFAULT_SORT_DATA]).split(',');
    this.predicate = sort[0];
    this.ascending = sort[1] === ASC;
  }

  protected onResponseSuccess(response: EntityArrayResponseType): void {
    const dataFromBody = this.fillComponentAttributesFromResponseBody(response.body);
    this.characterCards = this.refineData(dataFromBody);
  }

  protected refineData(data: ICharacterCard[]): ICharacterCard[] {
    return data.sort(this.sortService.startSort(this.predicate, this.ascending ? 1 : -1));
  }

  protected fillComponentAttributesFromResponseBody(data: ICharacterCard[] | null): ICharacterCard[] {
    return data ?? [];
  }

  protected queryBackend(predicate?: string, ascending?: boolean): Observable<EntityArrayResponseType> {
    this.isLoading = true;
    const queryObject = {
      eagerload: true,
      sort: this.getSortQueryParam(predicate, ascending),
    };
    return this.characterCardService.query(queryObject).pipe(tap(() => (this.isLoading = false)));
  }

  protected handleNavigation(predicate?: string, ascending?: boolean): void {
    const queryParamsObj = {
      sort: this.getSortQueryParam(predicate, ascending),
    };

    this.router.navigate(['./'], {
      relativeTo: this.activatedRoute,
      queryParams: queryParamsObj,
    });
  }

  protected getSortQueryParam(predicate = this.predicate, ascending = this.ascending): string[] {
    const ascendingQueryParam = ascending ? ASC : DESC;
    if (predicate === '') {
      return [];
    } else {
      return [predicate + ',' + ascendingQueryParam];
    }
  }
}

<div>
  <h2 id="page-heading" data-cy="CharacterCardHeading">
    <span jhiTranslate="elementaltakedownApp.characterCard.home.title">Character Archive</span>

    <div class="d-flex justify-content-end">
      <button class="btn btn-info me-2" (click)="load()" [disabled]="isLoading">
        <fa-icon icon="sync" [spin]="isLoading"></fa-icon>
        <span jhiTranslate="elementaltakedownApp.characterCard.home.refreshListLabel">Refresh list</span>
      </button>

<!--      <div *jhiHasAnyAuthority="'ROLE_ADMIN'">-->
        <button
          *jhiHasAnyAuthority="'ROLE_USER'"
          id="jh-create-entity"
          data-cy="entityCreateButton"
          class="btn btn-primary jh-create-entity modify-archive"
          [routerLink]="['/archive/edit']"
        >
          <fa-icon icon="plus"></fa-icon>
          <span> Add a Character to your Profile </span>
        </button>
<!--      </div>-->
    </div>
  </h2>

  <jhi-alert-error></jhi-alert-error>

  <jhi-alert></jhi-alert>

  <div class="alert alert-warning" id="no-result" *ngIf="characterCards?.length === 0">
    <span jhiTranslate="elementaltakedownApp.characterCard.home.notFound">No Character Cards found</span>
  </div>

  <div class="table-responsive table-entities" id="entities" *ngIf="characterCards && characterCards.length > 0">
    <table class="table table-striped" aria-describedby="page-heading">
      <thead>
        <tr jhiSort [(predicate)]="predicate" [(ascending)]="ascending" (sortChange)="navigateToWithComponentValues()">
          <th scope="col" jhiSortBy="id">
            <div class="d-flex">
              <span jhiTranslate="global.field.id">ID</span>
              <fa-icon class="p-1" icon="sort"></fa-icon>
            </div>
          </th>
          <th scope="col" jhiSortBy="name">
            <div class="d-flex">
              <span jhiTranslate="elementaltakedownApp.characterCard.name">Name</span>
              <fa-icon class="p-1" icon="sort"></fa-icon>
            </div>
          </th>
          <th scope="col" jhiSortBy="element">
            <div class="d-flex">
              <span jhiTranslate="elementaltakedownApp.characterCard.element">Element</span>
              <fa-icon class="p-1" icon="sort"></fa-icon>
            </div>
          </th>
          <th scope="col" jhiSortBy="basic.name">
            <div class="d-flex">
              <span jhiTranslate="elementaltakedownApp.characterCard.basic">Basic</span>
              <fa-icon class="p-1" icon="sort"></fa-icon>
            </div>
          </th>
          <th scope="col" jhiSortBy="skill.name">
            <div class="d-flex">
              <span jhiTranslate="elementaltakedownApp.characterCard.skill">Skill</span>
              <fa-icon class="p-1" icon="sort"></fa-icon>
            </div>
          </th>
          <th scope="col" jhiSortBy="ultimate.name">
            <div class="d-flex">
              <span jhiTranslate="elementaltakedownApp.characterCard.ultimate">Ultimate</span>
              <fa-icon class="p-1" icon="sort"></fa-icon>
            </div>
          </th>
          <th scope="col"></th>
        </tr>
      </thead>
      <tbody>
        <tr *ngFor="let characterCard of characterCards; trackBy: trackId" data-cy="entityTable">
          <td>
<!--            <a [routerLink]="['/character-card', characterCard.id, 'view']">-->
              {{ characterCard.id }}
<!--            </a>-->
          </td>
          <td>{{ characterCard.name }}</td>
          <td jhiTranslate="{{ 'elementaltakedownApp.ElementType.' + characterCard.element }}">{{ characterCard.element }}</td>
          <td>
            <div *ngIf="characterCard.basic">
<!--              <a [routerLink]="['/basic-atk', characterCard.basic.id, 'view']">-->
                {{ characterCard.basic.name }}
<!--              </a>-->
            </div>
          </td>
          <td>
            <div *ngIf="characterCard.skill">
<!--              <a [routerLink]="['/skill-atk', characterCard.skill.id, 'view']">-->
                {{ characterCard.skill.name }}
<!--              </a>-->
            </div>
          </td>
          <td>
            <div *ngIf="characterCard.ultimate">
<!--              <a [routerLink]="['/ultimate-atk', characterCard.ultimate.id, 'view']">-->
                {{ characterCard.ultimate.name }}
<!--              </a>-->
            </div>
          </td>
          <td class="text-end">
            <div class="btn-group">
              <button
                type="submit"
                [routerLink]="['/archive', characterCard.id, 'view']"
                class="btn btn-info btn-sm"
                data-cy="entityDetailsButton"
              >
                <fa-icon icon="eye"></fa-icon>
                <span class="d-none d-md-inline" jhiTranslate="entity.action.view">View</span>
              </button>

<!--              <button-->
<!--                type="submit"-->
<!--                [routerLink]="['/character-card', characterCard.id, 'edit']"-->
<!--                class="btn btn-primary btn-sm"-->
<!--                data-cy="entityEditButton"-->
<!--              >-->
<!--                <fa-icon icon="pencil-alt"></fa-icon>-->
<!--                <span class="d-none d-md-inline" jhiTranslate="entity.action.edit">Edit</span>-->
<!--              </button>-->

<!--              <button type="submit" (click)="delete(characterCard)" class="btn btn-danger btn-sm" data-cy="entityDeleteButton">-->
<!--                <fa-icon icon="times"></fa-icon>-->
<!--                <span class="d-none d-md-inline" jhiTranslate="entity.action.delete">Delete</span>-->
<!--              </button>-->
            </div>
          </td>
        </tr>
      </tbody>
    </table>
  </div>
</div>
