// elementaltakedown/src/main/webapp/app/entities/ultimate-atk/detail/ultimate-atk-detail.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute } from '@angular/router';

import { IUltimateATK } from '../ultimate-atk.model';

@Component({
  selector: 'jhi-ultimate-atk-detail',
  templateUrl: './ultimate-atk-detail.component.html',
})
export class UltimateATKDetailComponent implements OnInit {
  ultimateATK: IUltimateATK | null = null;

  constructor(protected activatedRoute: ActivatedRoute) {}

  ngOnInit(): void {
    this.activatedRoute.data.subscribe(({ ultimateATK }) => {
      this.ultimateATK = ultimateATK;
    });
  }

  previousState(): void {
    window.history.back();
  }
}

<div class="d-flex justify-content-center">
  <div class="col-8">
    <div *ngIf="ultimateATK">
      <h2 data-cy="ultimateATKDetailsHeading"><span jhiTranslate="elementaltakedownApp.ultimateATK.detail.title">Ultimate ATK</span></h2>

      <hr />

      <jhi-alert-error></jhi-alert-error>

      <jhi-alert></jhi-alert>

      <dl class="row-md jh-entity-details">
        <dt><span jhiTranslate="global.field.id">ID</span></dt>
        <dd>
          <span>{{ ultimateATK.id }}</span>
        </dd>
        <dt><span jhiTranslate="elementaltakedownApp.ultimateATK.name">Name</span></dt>
        <dd>
          <span>{{ ultimateATK.name }}</span>
        </dd>
        <dt><span jhiTranslate="elementaltakedownApp.ultimateATK.description">Description</span></dt>
        <dd>
          <span>{{ ultimateATK.description }}</span>
        </dd>
        <dt><span jhiTranslate="elementaltakedownApp.ultimateATK.requiredEnergy">Required Energy</span></dt>
        <dd>
          <span>{{ ultimateATK.requiredEnergy }}</span>
        </dd>
        <dt><span jhiTranslate="elementaltakedownApp.ultimateATK.damage">Damage</span></dt>
        <dd>
          <div *ngIf="ultimateATK.damage">
            <a [routerLink]="['/damage', ultimateATK.damage.id, 'view']">{{ ultimateATK.damage.name }}</a>
          </div>
        </dd>
      </dl>

      <button type="submit" (click)="previousState()" class="btn btn-info" data-cy="entityDetailsBackButton">
        <fa-icon icon="arrow-left"></fa-icon>&nbsp;<span jhiTranslate="entity.action.back">Back</span>
      </button>

      <button type="button" [routerLink]="['/ultimate-atk', ultimateATK.id, 'edit']" class="btn btn-primary">
        <fa-icon icon="pencil-alt"></fa-icon>&nbsp;<span jhiTranslate="entity.action.edit">Edit</span>
      </button>
    </div>
  </div>
</div>

// elementaltakedown/src/main/webapp/app/entities/ultimate-atk/ultimate-atk-detail.tsx
import React, { useEffect } from 'react';
import { Link, useParams } from 'react-router-dom';
import { Button, Row, Col } from 'reactstrap';
import { Translate } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { APP_DATE_FORMAT, APP_LOCAL_DATE_FORMAT } from 'app/config/constants';
import { useAppDispatch, useAppSelector } from 'app/config/store';

import { getEntity } from './ultimate-atk.reducer';

export const UltimateATKDetail = () => {
  const dispatch = useAppDispatch();

  const { id } = useParams<'id'>();

  useEffect(() => {
    dispatch(getEntity(id));
  }, []);

  const ultimateATKEntity = useAppSelector(state => state.ultimateATK.entity);
  return (
    <Row>
      <Col md="8">
        <h2 data-cy="ultimateATKDetailsHeading">
          <Translate contentKey="elementaltakedownApp.ultimateATK.detail.title">UltimateATK</Translate>
        </h2>
        <dl className="jh-entity-details">
          <dt>
            <span id="id">
              <Translate contentKey="global.field.id">ID</Translate>
            </span>
          </dt>
          <dd>{ultimateATKEntity.id}</dd>
          <dt>
            <span id="name">
              <Translate contentKey="elementaltakedownApp.ultimateATK.name">Name</Translate>
            </span>
          </dt>
          <dd>{ultimateATKEntity.name}</dd>
          <dt>
            <span id="description">
              <Translate contentKey="elementaltakedownApp.ultimateATK.description">Description</Translate>
            </span>
          </dt>
          <dd>{ultimateATKEntity.description}</dd>
          <dt>
            <span id="requiredEnergy">
              <Translate contentKey="elementaltakedownApp.ultimateATK.requiredEnergy">Required Energy</Translate>
            </span>
          </dt>
          <dd>{ultimateATKEntity.requiredEnergy}</dd>
          <dt>
            <Translate contentKey="elementaltakedownApp.ultimateATK.damage">Damage</Translate>
          </dt>
          <dd>{ultimateATKEntity.damage ? ultimateATKEntity.damage.name : ''}</dd>
        </dl>
        <Button tag={Link} to="/ultimate-atk" replace color="info" data-cy="entityDetailsBackButton">
          <FontAwesomeIcon icon="arrow-left" />{' '}
          <span className="d-none d-md-inline">
            <Translate contentKey="entity.action.back">Back</Translate>
          </span>
        </Button>
        &nbsp;
        <Button tag={Link} to={`/ultimate-atk/${ultimateATKEntity.id}/edit`} replace color="primary">
          <FontAwesomeIcon icon="pencil-alt" />{' '}
          <span className="d-none d-md-inline">
            <Translate contentKey="entity.action.edit">Edit</Translate>
          </span>
        </Button>
      </Col>
    </Row>
  );
};

export default UltimateATKDetail;
