// elementaltakedown/src/main/webapp/app/entities/basic-atk/basic-atk.tsx
import React, { useState, useEffect } from 'react';
import { Link, useLocation, useNavigate } from 'react-router-dom';
import { Button, Table } from 'reactstrap';
import { Translate } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { APP_DATE_FORMAT, APP_LOCAL_DATE_FORMAT } from 'app/config/constants';
import { useAppDispatch, useAppSelector } from 'app/config/store';

import { IBasicATK } from 'app/shared/model/basic-atk.model';
import { getEntities } from './basic-atk.reducer';

export const BasicATK = () => {
  const dispatch = useAppDispatch();

  const location = useLocation();
  const navigate = useNavigate();

  const basicATKList = useAppSelector(state => state.basicATK.entities);
  const loading = useAppSelector(state => state.basicATK.loading);

  useEffect(() => {
    dispatch(getEntities({}));
  }, []);

  const handleSyncList = () => {
    dispatch(getEntities({}));
  };

  return (
    <div>
      <h2 id="basic-atk-heading" data-cy="BasicATKHeading">
        <Translate contentKey="elementaltakedownApp.basicATK.home.title">Basic ATKS</Translate>
        <div className="d-flex justify-content-end">
          <Button className="me-2" color="info" onClick={handleSyncList} disabled={loading}>
            <FontAwesomeIcon icon="sync" spin={loading} />{' '}
            <Translate contentKey="elementaltakedownApp.basicATK.home.refreshListLabel">Refresh List</Translate>
          </Button>
          <Link to="/basic-atk/new" className="btn btn-primary jh-create-entity" id="jh-create-entity" data-cy="entityCreateButton">
            <FontAwesomeIcon icon="plus" />
            &nbsp;
            <Translate contentKey="elementaltakedownApp.basicATK.home.createLabel">Create new Basic ATK</Translate>
          </Link>
        </div>
      </h2>
      <div className="table-responsive">
        {basicATKList && basicATKList.length > 0 ? (
          <Table responsive>
            <thead>
              <tr>
                <th>
                  <Translate contentKey="elementaltakedownApp.basicATK.id">ID</Translate>
                </th>
                <th>
                  <Translate contentKey="elementaltakedownApp.basicATK.name">Name</Translate>
                </th>
                <th>
                  <Translate contentKey="elementaltakedownApp.basicATK.description">Description</Translate>
                </th>
                <th>
                  <Translate contentKey="elementaltakedownApp.basicATK.damage">Damage</Translate>
                </th>
                <th />
              </tr>
            </thead>
            <tbody>
              {basicATKList.map((basicATK, i) => (
                <tr key={`entity-${i}`} data-cy="entityTable">
                  <td>
                    <Button tag={Link} to={`/basic-atk/${basicATK.id}`} color="link" size="sm">
                      {basicATK.id}
                    </Button>
                  </td>
                  <td>{basicATK.name}</td>
                  <td>{basicATK.description}</td>
                  <td>{basicATK.damage ? <Link to={`/damage/${basicATK.damage.id}`}>{basicATK.damage.name}</Link> : ''}</td>
                  <td className="text-end">
                    <div className="btn-group flex-btn-group-container">
                      <Button tag={Link} to={`/basic-atk/${basicATK.id}`} color="info" size="sm" data-cy="entityDetailsButton">
                        <FontAwesomeIcon icon="eye" />{' '}
                        <span className="d-none d-md-inline">
                          <Translate contentKey="entity.action.view">View</Translate>
                        </span>
                      </Button>
                      <Button tag={Link} to={`/basic-atk/${basicATK.id}/edit`} color="primary" size="sm" data-cy="entityEditButton">
                        <FontAwesomeIcon icon="pencil-alt" />{' '}
                        <span className="d-none d-md-inline">
                          <Translate contentKey="entity.action.edit">Edit</Translate>
                        </span>
                      </Button>
                      <Button tag={Link} to={`/basic-atk/${basicATK.id}/delete`} color="danger" size="sm" data-cy="entityDeleteButton">
                        <FontAwesomeIcon icon="trash" />{' '}
                        <span className="d-none d-md-inline">
                          <Translate contentKey="entity.action.delete">Delete</Translate>
                        </span>
                      </Button>
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </Table>
        ) : (
          !loading && (
            <div className="alert alert-warning">
              <Translate contentKey="elementaltakedownApp.basicATK.home.notFound">No Basic ATKS found</Translate>
            </div>
          )
        )}
      </div>
    </div>
  );
};

export default BasicATK;

// elementaltakedown/src/main/webapp/app/entities/basic-atk/list/basic-atk.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute, Data, ParamMap, Router } from '@angular/router';
import { combineLatest, filter, Observable, switchMap, tap } from 'rxjs';
import { NgbModal } from '@ng-bootstrap/ng-bootstrap';

import { IBasicATK } from '../basic-atk.model';
import { ASC, DESC, SORT, ITEM_DELETED_EVENT, DEFAULT_SORT_DATA } from 'app/config/navigation.constants';
import { EntityArrayResponseType, BasicATKService } from '../service/basic-atk.service';
import { BasicATKDeleteDialogComponent } from '../delete/basic-atk-delete-dialog.component';
import { SortService } from 'app/shared/sort/sort.service';

@Component({
  selector: 'jhi-basic-atk',
  templateUrl: './basic-atk.component.html',
})
export class BasicATKComponent implements OnInit {
  basicATKS?: IBasicATK[];
  isLoading = false;

  predicate = 'id';
  ascending = true;

  constructor(
    protected basicATKService: BasicATKService,
    protected activatedRoute: ActivatedRoute,
    public router: Router,
    protected sortService: SortService,
    protected modalService: NgbModal
  ) {}

  trackId = (_index: number, item: IBasicATK): number => this.basicATKService.getBasicATKIdentifier(item);

  ngOnInit(): void {
    this.load();
  }

  delete(basicATK: IBasicATK): void {
    const modalRef = this.modalService.open(BasicATKDeleteDialogComponent, { size: 'lg', backdrop: 'static' });
    modalRef.componentInstance.basicATK = basicATK;
    // unsubscribe not needed because closed completes on modal close
    modalRef.closed
      .pipe(
        filter(reason => reason === ITEM_DELETED_EVENT),
        switchMap(() => this.loadFromBackendWithRouteInformations())
      )
      .subscribe({
        next: (res: EntityArrayResponseType) => {
          this.onResponseSuccess(res);
        },
      });
  }

  load(): void {
    this.loadFromBackendWithRouteInformations().subscribe({
      next: (res: EntityArrayResponseType) => {
        this.onResponseSuccess(res);
      },
    });
  }

  navigateToWithComponentValues(): void {
    this.handleNavigation(this.predicate, this.ascending);
  }

  protected loadFromBackendWithRouteInformations(): Observable<EntityArrayResponseType> {
    return combineLatest([this.activatedRoute.queryParamMap, this.activatedRoute.data]).pipe(
      tap(([params, data]) => this.fillComponentAttributeFromRoute(params, data)),
      switchMap(() => this.queryBackend(this.predicate, this.ascending))
    );
  }

  protected fillComponentAttributeFromRoute(params: ParamMap, data: Data): void {
    const sort = (params.get(SORT) ?? data[DEFAULT_SORT_DATA]).split(',');
    this.predicate = sort[0];
    this.ascending = sort[1] === ASC;
  }

  protected onResponseSuccess(response: EntityArrayResponseType): void {
    const dataFromBody = this.fillComponentAttributesFromResponseBody(response.body);
    this.basicATKS = this.refineData(dataFromBody);
  }

  protected refineData(data: IBasicATK[]): IBasicATK[] {
    return data.sort(this.sortService.startSort(this.predicate, this.ascending ? 1 : -1));
  }

  protected fillComponentAttributesFromResponseBody(data: IBasicATK[] | null): IBasicATK[] {
    return data ?? [];
  }

  protected queryBackend(predicate?: string, ascending?: boolean): Observable<EntityArrayResponseType> {
    this.isLoading = true;
    const queryObject = {
      eagerload: true,
      sort: this.getSortQueryParam(predicate, ascending),
    };
    return this.basicATKService.query(queryObject).pipe(tap(() => (this.isLoading = false)));
  }

  protected handleNavigation(predicate?: string, ascending?: boolean): void {
    const queryParamsObj = {
      sort: this.getSortQueryParam(predicate, ascending),
    };

    this.router.navigate(['./'], {
      relativeTo: this.activatedRoute,
      queryParams: queryParamsObj,
    });
  }

  protected getSortQueryParam(predicate = this.predicate, ascending = this.ascending): string[] {
    const ascendingQueryParam = ascending ? ASC : DESC;
    if (predicate === '') {
      return [];
    } else {
      return [predicate + ',' + ascendingQueryParam];
    }
  }
}

<div>
  <h2 id="page-heading" data-cy="BasicATKHeading">
    <span jhiTranslate="elementaltakedownApp.basicATK.home.title">Basic ATKS</span>

    <div class="d-flex justify-content-end">
      <button class="btn btn-info me-2" (click)="load()" [disabled]="isLoading">
        <fa-icon icon="sync" [spin]="isLoading"></fa-icon>
        <span jhiTranslate="elementaltakedownApp.basicATK.home.refreshListLabel">Refresh list</span>
      </button>

      <button
        id="jh-create-entity"
        data-cy="entityCreateButton"
        class="btn btn-primary jh-create-entity create-basic-atk"
        [routerLink]="['/basic-atk/new']"
      >
        <fa-icon icon="plus"></fa-icon>
        <span jhiTranslate="elementaltakedownApp.basicATK.home.createLabel"> Create a new Basic ATK </span>
      </button>
    </div>
  </h2>

  <jhi-alert-error></jhi-alert-error>

  <jhi-alert></jhi-alert>

  <div class="alert alert-warning" id="no-result" *ngIf="basicATKS?.length === 0">
    <span jhiTranslate="elementaltakedownApp.basicATK.home.notFound">No Basic ATKS found</span>
  </div>

  <div class="table-responsive table-entities" id="entities" *ngIf="basicATKS && basicATKS.length > 0">
    <table class="table table-striped" aria-describedby="page-heading">
      <thead>
        <tr jhiSort [(predicate)]="predicate" [(ascending)]="ascending" (sortChange)="navigateToWithComponentValues()">
          <th scope="col" jhiSortBy="id">
            <div class="d-flex">
              <span jhiTranslate="global.field.id">ID</span>
              <fa-icon class="p-1" icon="sort"></fa-icon>
            </div>
          </th>
          <th scope="col" jhiSortBy="name">
            <div class="d-flex">
              <span jhiTranslate="elementaltakedownApp.basicATK.name">Name</span>
              <fa-icon class="p-1" icon="sort"></fa-icon>
            </div>
          </th>
          <th scope="col" jhiSortBy="damage.name">
            <div class="d-flex">
              <span jhiTranslate="elementaltakedownApp.basicATK.damage">Damage</span>
              <fa-icon class="p-1" icon="sort"></fa-icon>
            </div>
          </th>
          <th scope="col"></th>
        </tr>
      </thead>
      <tbody>
        <tr *ngFor="let basicATK of basicATKS; trackBy: trackId" data-cy="entityTable">
          <td>
            <a [routerLink]="['/basic-atk', basicATK.id, 'view']">{{ basicATK.id }}</a>
          </td>
          <td>{{ basicATK.name }}</td>
          <td>
            <div *ngIf="basicATK.damage">
              <a [routerLink]="['/damage', basicATK.damage.id, 'view']">{{ basicATK.damage.name }}</a>
            </div>
          </td>
          <td class="text-end">
            <div class="btn-group">
              <button
                type="submit"
                [routerLink]="['/basic-atk', basicATK.id, 'view']"
                class="btn btn-info btn-sm"
                data-cy="entityDetailsButton"
              >
                <fa-icon icon="eye"></fa-icon>
                <span class="d-none d-md-inline" jhiTranslate="entity.action.view">View</span>
              </button>

              <button
                type="submit"
                [routerLink]="['/basic-atk', basicATK.id, 'edit']"
                class="btn btn-primary btn-sm"
                data-cy="entityEditButton"
              >
                <fa-icon icon="pencil-alt"></fa-icon>
                <span class="d-none d-md-inline" jhiTranslate="entity.action.edit">Edit</span>
              </button>

              <button type="submit" (click)="delete(basicATK)" class="btn btn-danger btn-sm" data-cy="entityDeleteButton">
                <fa-icon icon="times"></fa-icon>
                <span class="d-none d-md-inline" jhiTranslate="entity.action.delete">Delete</span>
              </button>
            </div>
          </td>
        </tr>
      </tbody>
    </table>
  </div>
</div>
