// elementaltakedown/src/main/webapp/app/entities/damage/damage-update.tsx
import React, { useState, useEffect } from 'react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import { Button, Row, Col, FormText } from 'reactstrap';
import { isNumber, Translate, translate, ValidatedField, ValidatedForm } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { convertDateTimeFromServer, convertDateTimeToServer, displayDefaultDateTime } from 'app/shared/util/date-utils';
import { mapIdList } from 'app/shared/util/entity-utils';
import { useAppDispatch, useAppSelector } from 'app/config/store';

import { IDamage } from 'app/shared/model/damage.model';
import { DmgElementType } from 'app/shared/model/enumerations/dmg-element-type.model';
import { getEntity, updateEntity, createEntity, reset } from './damage.reducer';

export const DamageUpdate = () => {
  const dispatch = useAppDispatch();

  const navigate = useNavigate();

  const { id } = useParams<'id'>();
  const isNew = id === undefined;

  const damageEntity = useAppSelector(state => state.damage.entity);
  const loading = useAppSelector(state => state.damage.loading);
  const updating = useAppSelector(state => state.damage.updating);
  const updateSuccess = useAppSelector(state => state.damage.updateSuccess);
  const dmgElementTypeValues = Object.keys(DmgElementType);

  const handleClose = () => {
    navigate('/damage');
  };

  useEffect(() => {
    if (isNew) {
      dispatch(reset());
    } else {
      dispatch(getEntity(id));
    }
  }, []);

  useEffect(() => {
    if (updateSuccess) {
      handleClose();
    }
  }, [updateSuccess]);

  const saveEntity = values => {
    const entity = {
      ...damageEntity,
      ...values,
    };

    if (isNew) {
      dispatch(createEntity(entity));
    } else {
      dispatch(updateEntity(entity));
    }
  };

  const defaultValues = () =>
    isNew
      ? {}
      : {
          dmgElement: 'WATER',
          splashElement: 'WATER',
          ...damageEntity,
        };

  return (
    <div>
      <Row className="justify-content-center">
        <Col md="8">
          <h2 id="elementaltakedownApp.damage.home.createOrEditLabel" data-cy="DamageCreateUpdateHeading">
            <Translate contentKey="elementaltakedownApp.damage.home.createOrEditLabel">Create or edit a Damage</Translate>
          </h2>
        </Col>
      </Row>
      <Row className="justify-content-center">
        <Col md="8">
          {loading ? (
            <p>Loading...</p>
          ) : (
            <ValidatedForm defaultValues={defaultValues()} onSubmit={saveEntity}>
              {!isNew ? (
                <ValidatedField
                  name="id"
                  required
                  readOnly
                  id="damage-id"
                  label={translate('global.field.id')}
                  validate={{ required: true }}
                />
              ) : null}
              <ValidatedField
                label={translate('elementaltakedownApp.damage.name')}
                id="damage-name"
                name="name"
                data-cy="name"
                type="text"
              />
              <ValidatedField
                label={translate('elementaltakedownApp.damage.dmgValue')}
                id="damage-dmgValue"
                name="dmgValue"
                data-cy="dmgValue"
                type="text"
                validate={{
                  required: { value: true, message: translate('entity.validation.required') },
                  validate: v => isNumber(v) || translate('entity.validation.number'),
                }}
              />
              <ValidatedField
                label={translate('elementaltakedownApp.damage.dmgElement')}
                id="damage-dmgElement"
                name="dmgElement"
                data-cy="dmgElement"
                type="select"
              >
                {dmgElementTypeValues.map(dmgElementType => (
                  <option value={dmgElementType} key={dmgElementType}>
                    {translate('elementaltakedownApp.DmgElementType.' + dmgElementType)}
                  </option>
                ))}
              </ValidatedField>
              <ValidatedField
                label={translate('elementaltakedownApp.damage.splashDmg')}
                id="damage-splashDmg"
                name="splashDmg"
                data-cy="splashDmg"
                type="text"
              />
              <ValidatedField
                label={translate('elementaltakedownApp.damage.splashElement')}
                id="damage-splashElement"
                name="splashElement"
                data-cy="splashElement"
                type="select"
              >
                {dmgElementTypeValues.map(dmgElementType => (
                  <option value={dmgElementType} key={dmgElementType}>
                    {translate('elementaltakedownApp.DmgElementType.' + dmgElementType)}
                  </option>
                ))}
              </ValidatedField>
              <Button tag={Link} id="cancel-save" data-cy="entityCreateCancelButton" to="/damage" replace color="info">
                <FontAwesomeIcon icon="arrow-left" />
                &nbsp;
                <span className="d-none d-md-inline">
                  <Translate contentKey="entity.action.back">Back</Translate>
                </span>
              </Button>
              &nbsp;
              <Button color="primary" id="save-entity" data-cy="entityCreateSaveButton" type="submit" disabled={updating}>
                <FontAwesomeIcon icon="save" />
                &nbsp;
                <Translate contentKey="entity.action.save">Save</Translate>
              </Button>
            </ValidatedForm>
          )}
        </Col>
      </Row>
    </div>
  );
};

export default DamageUpdate;

// elementaltakedown/src/main/webapp/app/entities/damage/update/damage-update.component.ts
import { Component, OnInit } from '@angular/core';
import { HttpResponse } from '@angular/common/http';
import { ActivatedRoute } from '@angular/router';
import { Observable } from 'rxjs';
import { finalize } from 'rxjs/operators';

import { DamageFormService, DamageFormGroup } from './damage-form.service';
import { IDamage } from '../damage.model';
import { DamageService } from '../service/damage.service';
import { DmgElementType } from 'app/entities/enumerations/dmg-element-type.model';

@Component({
  selector: 'jhi-damage-update',
  templateUrl: './damage-update.component.html',
})
export class DamageUpdateComponent implements OnInit {
  isSaving = false;
  damage: IDamage | null = null;
  dmgElementTypeValues = Object.keys(DmgElementType);

  editForm: DamageFormGroup = this.damageFormService.createDamageFormGroup();

  constructor(
    protected damageService: DamageService,
    protected damageFormService: DamageFormService,
    protected activatedRoute: ActivatedRoute
  ) {}

  ngOnInit(): void {
    this.activatedRoute.data.subscribe(({ damage }) => {
      this.damage = damage;
      if (damage) {
        this.updateForm(damage);
      }
    });
  }

  previousState(): void {
    window.history.back();
  }

  save(): void {
    this.isSaving = true;
    const damage = this.damageFormService.getDamage(this.editForm);
    if (damage.id !== null) {
      this.subscribeToSaveResponse(this.damageService.update(damage));
    } else {
      this.subscribeToSaveResponse(this.damageService.create(damage));
    }
  }

  protected subscribeToSaveResponse(result: Observable<HttpResponse<IDamage>>): void {
    result.pipe(finalize(() => this.onSaveFinalize())).subscribe({
      next: () => this.onSaveSuccess(),
      error: () => this.onSaveError(),
    });
  }

  protected onSaveSuccess(): void {
    this.previousState();
  }

  protected onSaveError(): void {
    // Api for inheritance.
  }

  protected onSaveFinalize(): void {
    this.isSaving = false;
  }

  protected updateForm(damage: IDamage): void {
    this.damage = damage;
    this.damageFormService.resetForm(this.editForm, damage);
  }
}

<div class="d-flex justify-content-center">
  <div class="col-8">
    <form name="editForm" role="form" novalidate (ngSubmit)="save()" [formGroup]="editForm">
      <h2 id="jhi-damage-heading" data-cy="DamageCreateUpdateHeading" jhiTranslate="elementaltakedownApp.damage.home.createOrEditLabel">
        Create or edit a Damage
      </h2>

      <div>
        <jhi-alert-error></jhi-alert-error>

        <div class="row mb-3" *ngIf="editForm.controls.id.value !== null">
          <label class="form-label" jhiTranslate="global.field.id" for="field_id">ID</label>
          <input type="number" class="form-control" name="id" id="field_id" data-cy="id" formControlName="id" [readonly]="true" />
        </div>

<!--        <div class="row mb-3">-->
<!--          <label class="form-label" jhiTranslate="elementaltakedownApp.damage.name" for="field_name">Name</label>-->
<!--          <input type="text" class="form-control" name="name" id="field_name" data-cy="name" formControlName="name" />-->
<!--        </div>-->

        <div class="row mb-3">
          <label class="form-label" jhiTranslate="elementaltakedownApp.damage.dmgValue" for="field_dmgValue">Dmg Value</label>
          <input type="number" class="form-control" name="dmgValue" id="field_dmgValue" data-cy="dmgValue" formControlName="dmgValue" />
          <div *ngIf="editForm.get('dmgValue')!.invalid && (editForm.get('dmgValue')!.dirty || editForm.get('dmgValue')!.touched)">
            <small
              class="form-text text-danger"
              *ngIf="editForm.get('dmgValue')?.errors?.required"
              jhiTranslate="entity.validation.required"
            >
              This field is required.
            </small>
            <small
              class="form-text text-danger"
              [hidden]="!editForm.get('dmgValue')?.errors?.number"
              jhiTranslate="entity.validation.number"
            >
              This field should be a number.
            </small>
          </div>
        </div>

        <div class="row mb-3">
          <label class="form-label" jhiTranslate="elementaltakedownApp.damage.dmgElement" for="field_dmgElement">Dmg Element</label>
          <select class="form-control" name="dmgElement" formControlName="dmgElement" id="field_dmgElement" data-cy="dmgElement">
            <option [ngValue]="null">{{ 'elementaltakedownApp.DmgElementType.null' | translate }}</option>
            <option *ngFor="let dmgElementType of dmgElementTypeValues" [value]="dmgElementType">
              {{ 'elementaltakedownApp.DmgElementType.' + dmgElementType | translate }}
            </option>
          </select>
          <div *ngIf="editForm.get('dmgElement')!.invalid && (editForm.get('dmgElement')!.dirty || editForm.get('dmgElement')!.touched)">
            <small
              class="form-text text-danger"
              *ngIf="editForm.get('dmgElement')?.errors?.required"
              jhiTranslate="entity.validation.required"
            >
              This field is required.
            </small>
          </div>
        </div>

        <div class="row mb-3">
          <label class="form-label" jhiTranslate="elementaltakedownApp.damage.splashDmg" for="field_splashDmg">Splash Dmg</label>
          <input type="number" class="form-control" name="splashDmg" id="field_splashDmg" data-cy="splashDmg" formControlName="splashDmg" />
        </div>

        <div class="row mb-3">
          <label class="form-label" jhiTranslate="elementaltakedownApp.damage.splashElement" for="field_splashElement"
            >Splash Element</label
          >
          <select
            class="form-control"
            name="splashElement"
            formControlName="splashElement"
            id="field_splashElement"
            data-cy="splashElement"
          >
            <option [ngValue]="null">{{ 'elementaltakedownApp.DmgElementType.null' | translate }}</option>
            <option *ngFor="let dmgElementType of dmgElementTypeValues" [value]="dmgElementType">
              {{ 'elementaltakedownApp.DmgElementType.' + dmgElementType | translate }}
            </option>
          </select>
        </div>
      </div>

      <div>
        <button type="button" id="cancel-save" data-cy="entityCreateCancelButton" class="btn btn-secondary" (click)="previousState()">
          <fa-icon icon="ban"></fa-icon>&nbsp;<span jhiTranslate="entity.action.cancel">Cancel</span>
        </button>

        <button
          type="submit"
          id="save-entity"
          data-cy="entityCreateSaveButton"
          [disabled]="editForm.invalid || isSaving"
          class="btn btn-primary"
        >
          <fa-icon icon="save"></fa-icon>&nbsp;<span jhiTranslate="entity.action.save">Save</span>
        </button>
      </div>
    </form>
  </div>
</div>
