// elementaltakedown/src/main/webapp/app/entities/skill-atk/detail/skill-atk-detail.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute } from '@angular/router';

import { ISkillATK } from '../skill-atk.model';

@Component({
  selector: 'jhi-skill-atk-detail',
  templateUrl: './skill-atk-detail.component.html',
})
export class SkillATKDetailComponent implements OnInit {
  skillATK: ISkillATK | null = null;

  constructor(protected activatedRoute: ActivatedRoute) {}

  ngOnInit(): void {
    this.activatedRoute.data.subscribe(({ skillATK }) => {
      this.skillATK = skillATK;
    });
  }

  previousState(): void {
    window.history.back();
  }
}

<div class="d-flex justify-content-center">
  <div class="col-8">
    <div *ngIf="skillATK">
      <h2 data-cy="skillATKDetailsHeading"><span jhiTranslate="elementaltakedownApp.skillATK.detail.title">Skill ATK</span></h2>

      <hr />

      <jhi-alert-error></jhi-alert-error>

      <jhi-alert></jhi-alert>

      <dl class="row-md jh-entity-details">
        <dt><span jhiTranslate="global.field.id">ID</span></dt>
        <dd>
          <span>{{ skillATK.id }}</span>
        </dd>
        <dt><span jhiTranslate="elementaltakedownApp.skillATK.name">Name</span></dt>
        <dd>
          <span>{{ skillATK.name }}</span>
        </dd>
        <dt><span jhiTranslate="elementaltakedownApp.skillATK.description">Description</span></dt>
        <dd>
          <span>{{ skillATK.description }}</span>
        </dd>
        <dt><span jhiTranslate="elementaltakedownApp.skillATK.damage">Damage</span></dt>
        <dd>
          <div *ngIf="skillATK.damage">
            <a [routerLink]="['/damage', skillATK.damage.id, 'view']">{{ skillATK.damage.name }}</a>
          </div>
        </dd>
      </dl>

      <button type="submit" (click)="previousState()" class="btn btn-info" data-cy="entityDetailsBackButton">
        <fa-icon icon="arrow-left"></fa-icon>&nbsp;<span jhiTranslate="entity.action.back">Back</span>
      </button>

      <button type="button" [routerLink]="['/skill-atk', skillATK.id, 'edit']" class="btn btn-primary">
        <fa-icon icon="pencil-alt"></fa-icon>&nbsp;<span jhiTranslate="entity.action.edit">Edit</span>
      </button>
    </div>
  </div>
</div>

// elementaltakedown/src/main/webapp/app/entities/skill-atk/skill-atk-detail.tsx
import React, { useEffect } from 'react';
import { Link, useParams } from 'react-router-dom';
import { Button, Row, Col } from 'reactstrap';
import { Translate } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { APP_DATE_FORMAT, APP_LOCAL_DATE_FORMAT } from 'app/config/constants';
import { useAppDispatch, useAppSelector } from 'app/config/store';

import { getEntity } from './skill-atk.reducer';

export const SkillATKDetail = () => {
  const dispatch = useAppDispatch();

  const { id } = useParams<'id'>();

  useEffect(() => {
    dispatch(getEntity(id));
  }, []);

  const skillATKEntity = useAppSelector(state => state.skillATK.entity);
  return (
    <Row>
      <Col md="8">
        <h2 data-cy="skillATKDetailsHeading">
          <Translate contentKey="elementaltakedownApp.skillATK.detail.title">SkillATK</Translate>
        </h2>
        <dl className="jh-entity-details">
          <dt>
            <span id="id">
              <Translate contentKey="global.field.id">ID</Translate>
            </span>
          </dt>
          <dd>{skillATKEntity.id}</dd>
          <dt>
            <span id="name">
              <Translate contentKey="elementaltakedownApp.skillATK.name">Name</Translate>
            </span>
          </dt>
          <dd>{skillATKEntity.name}</dd>
          <dt>
            <span id="description">
              <Translate contentKey="elementaltakedownApp.skillATK.description">Description</Translate>
            </span>
          </dt>
          <dd>{skillATKEntity.description}</dd>
          <dt>
            <Translate contentKey="elementaltakedownApp.skillATK.damage">Damage</Translate>
          </dt>
          <dd>{skillATKEntity.damage ? skillATKEntity.damage.name : ''}</dd>
        </dl>
        <Button tag={Link} to="/skill-atk" replace color="info" data-cy="entityDetailsBackButton">
          <FontAwesomeIcon icon="arrow-left" />{' '}
          <span className="d-none d-md-inline">
            <Translate contentKey="entity.action.back">Back</Translate>
          </span>
        </Button>
        &nbsp;
        <Button tag={Link} to={`/skill-atk/${skillATKEntity.id}/edit`} replace color="primary">
          <FontAwesomeIcon icon="pencil-alt" />{' '}
          <span className="d-none d-md-inline">
            <Translate contentKey="entity.action.edit">Edit</Translate>
          </span>
        </Button>
      </Col>
    </Row>
  );
};

export default SkillATKDetail;
