// elementaltakedown/src/main/webapp/app/entities/character-card/character-card-detail.tsx
import React, { useEffect } from 'react';
import { Link, useParams } from 'react-router-dom';
import { Button, Row, Col } from 'reactstrap';
import { Translate } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { APP_DATE_FORMAT, APP_LOCAL_DATE_FORMAT } from 'app/config/constants';
import { useAppDispatch, useAppSelector } from 'app/config/store';

import { getEntity } from './character-card.reducer';

export const CharacterCardDetail = () => {
  const dispatch = useAppDispatch();

  const { id } = useParams<'id'>();

  useEffect(() => {
    dispatch(getEntity(id));
  }, []);

  const characterCardEntity = useAppSelector(state => state.characterCard.entity);
  return (
    <Row>
      <Col md="8">
        <h2 data-cy="characterCardDetailsHeading">
          <Translate contentKey="elementaltakedownApp.characterCard.detail.title">CharacterCard</Translate>
        </h2>
        <dl className="jh-entity-details">
          <dt>
            <span id="id">
              <Translate contentKey="global.field.id">ID</Translate>
            </span>
          </dt>
          <dd>{characterCardEntity.id}</dd>
          <dt>
            <span id="name">
              <Translate contentKey="elementaltakedownApp.characterCard.name">Name</Translate>
            </span>
          </dt>
          <dd>{characterCardEntity.name}</dd>
          <dt>
            <span id="element">
              <Translate contentKey="elementaltakedownApp.characterCard.element">Element</Translate>
            </span>
          </dt>
          <dd>{characterCardEntity.element}</dd>
          <dt>
            <Translate contentKey="elementaltakedownApp.characterCard.basic">Basic</Translate>
          </dt>
          <dd>{characterCardEntity.basic ? characterCardEntity.basic.name : ''}</dd>
          <dt>
            <Translate contentKey="elementaltakedownApp.characterCard.skill">Skill</Translate>
          </dt>
          <dd>{characterCardEntity.skill ? characterCardEntity.skill.name : ''}</dd>
          <dt>
            <Translate contentKey="elementaltakedownApp.characterCard.ultimate">Ultimate</Translate>
          </dt>
          <dd>{characterCardEntity.ultimate ? characterCardEntity.ultimate.name : ''}</dd>
        </dl>
        <Button tag={Link} to="/character-card" replace color="info" data-cy="entityDetailsBackButton">
          <FontAwesomeIcon icon="arrow-left" />{' '}
          <span className="d-none d-md-inline">
            <Translate contentKey="entity.action.back">Back</Translate>
          </span>
        </Button>
        &nbsp;
        <Button tag={Link} to={`/character-card/${characterCardEntity.id}/edit`} replace color="primary">
          <FontAwesomeIcon icon="pencil-alt" />{' '}
          <span className="d-none d-md-inline">
            <Translate contentKey="entity.action.edit">Edit</Translate>
          </span>
        </Button>
      </Col>
    </Row>
  );
};

export default CharacterCardDetail;

// elementaltakedown/src/main/webapp/app/archive/detail/character-card-detail.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute } from '@angular/router';

import { ICharacterCard } from '../character-card.model';

@Component({
  selector: 'jhi-character-card-detail',
  templateUrl: './character-card-detail.component.html',
})
export class CharacterCardDetailComponent implements OnInit {
  characterCard: ICharacterCard | null = null;

  constructor(protected activatedRoute: ActivatedRoute) {}

  ngOnInit(): void {
    this.activatedRoute.data.subscribe(({ characterCard }) => {
      this.characterCard = characterCard;
//       console.log(this.characterCard);
    });
  }

  previousState(): void {
    window.history.back();
  }
}

<div class="d-flex justify-content-center">
  <div class="col-8">
    <div *ngIf="characterCard">
      <h2 data-cy="characterCardDetailsHeading">
        <span jhiTranslate="elementaltakedownApp.characterCard.detail.title">Character Card</span>
      </h2>

      <hr />

      <jhi-alert-error></jhi-alert-error>

      <jhi-alert></jhi-alert>

      <dl class="row-md jh-entity-details">
<!--        <dt><span jhiTranslate="global.field.id">ID</span></dt>-->
<!--        <dd>-->
<!--          <span>{{ characterCard.id }}</span>-->
<!--        </dd>-->
        <dt><span jhiTranslate="elementaltakedownApp.characterCard.name">Name</span></dt>
        <dd>
          <span>{{ characterCard.name }}</span>
        </dd>
        <dt><span jhiTranslate="elementaltakedownApp.characterCard.element">Element</span></dt>
        <dd>
          <span jhiTranslate="{{ 'elementaltakedownApp.ElementType.' + characterCard.element }}">{{ characterCard.element }}</span>
        </dd>
        <dt><span jhiTranslate="elementaltakedownApp.characterCard.basic">Basic</span></dt>
        <dd>
          <div *ngIf="characterCard.basic">
            {{ characterCard.basic.name }} <br>
            <em>{{ characterCard.basic.description }}</em>
          </div>
        </dd>
        <dt><span jhiTranslate="elementaltakedownApp.characterCard.skill">Skill</span></dt>
        <dd>
          <div *ngIf="characterCard.skill">
            {{ characterCard.skill.name }} <br>
            <em>{{ characterCard.skill.description }}</em>
          </div>
        </dd>
        <dt><span jhiTranslate="elementaltakedownApp.characterCard.ultimate">Ultimate</span></dt>
        <dd>
          <div *ngIf="characterCard.ultimate">
            {{ characterCard.ultimate.name }} <br>
            <em>Costs {{ characterCard.ultimate.requiredEnergy }} energy; {{ characterCard.ultimate.description }}</em>
          </div>
        </dd>
      </dl>

      <button type="submit" (click)="previousState()" class="btn btn-info" data-cy="entityDetailsBackButton">
        <fa-icon icon="arrow-left"></fa-icon>&nbsp;<span jhiTranslate="entity.action.back">Back</span>
      </button>

    </div>
  </div>
</div>
