// elementaltakedown/src/main/webapp/app/entities/skill-atk/skill-atk.tsx
import React, { useState, useEffect } from 'react';
import { Link, useLocation, useNavigate } from 'react-router-dom';
import { Button, Table } from 'reactstrap';
import { Translate } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { APP_DATE_FORMAT, APP_LOCAL_DATE_FORMAT } from 'app/config/constants';
import { useAppDispatch, useAppSelector } from 'app/config/store';

import { ISkillATK } from 'app/shared/model/skill-atk.model';
import { getEntities } from './skill-atk.reducer';

export const SkillATK = () => {
  const dispatch = useAppDispatch();

  const location = useLocation();
  const navigate = useNavigate();

  const skillATKList = useAppSelector(state => state.skillATK.entities);
  const loading = useAppSelector(state => state.skillATK.loading);

  useEffect(() => {
    dispatch(getEntities({}));
  }, []);

  const handleSyncList = () => {
    dispatch(getEntities({}));
  };

  return (
    <div>
      <h2 id="skill-atk-heading" data-cy="SkillATKHeading">
        <Translate contentKey="elementaltakedownApp.skillATK.home.title">Skill ATKS</Translate>
        <div className="d-flex justify-content-end">
          <Button className="me-2" color="info" onClick={handleSyncList} disabled={loading}>
            <FontAwesomeIcon icon="sync" spin={loading} />{' '}
            <Translate contentKey="elementaltakedownApp.skillATK.home.refreshListLabel">Refresh List</Translate>
          </Button>
          <Link to="/skill-atk/new" className="btn btn-primary jh-create-entity" id="jh-create-entity" data-cy="entityCreateButton">
            <FontAwesomeIcon icon="plus" />
            &nbsp;
            <Translate contentKey="elementaltakedownApp.skillATK.home.createLabel">Create new Skill ATK</Translate>
          </Link>
        </div>
      </h2>
      <div className="table-responsive">
        {skillATKList && skillATKList.length > 0 ? (
          <Table responsive>
            <thead>
              <tr>
                <th>
                  <Translate contentKey="elementaltakedownApp.skillATK.id">ID</Translate>
                </th>
                <th>
                  <Translate contentKey="elementaltakedownApp.skillATK.name">Name</Translate>
                </th>
                <th>
                  <Translate contentKey="elementaltakedownApp.skillATK.description">Description</Translate>
                </th>
                <th>
                  <Translate contentKey="elementaltakedownApp.skillATK.damage">Damage</Translate>
                </th>
                <th />
              </tr>
            </thead>
            <tbody>
              {skillATKList.map((skillATK, i) => (
                <tr key={`entity-${i}`} data-cy="entityTable">
                  <td>
                    <Button tag={Link} to={`/skill-atk/${skillATK.id}`} color="link" size="sm">
                      {skillATK.id}
                    </Button>
                  </td>
                  <td>{skillATK.name}</td>
                  <td>{skillATK.description}</td>
                  <td>{skillATK.damage ? <Link to={`/damage/${skillATK.damage.id}`}>{skillATK.damage.name}</Link> : ''}</td>
                  <td className="text-end">
                    <div className="btn-group flex-btn-group-container">
                      <Button tag={Link} to={`/skill-atk/${skillATK.id}`} color="info" size="sm" data-cy="entityDetailsButton">
                        <FontAwesomeIcon icon="eye" />{' '}
                        <span className="d-none d-md-inline">
                          <Translate contentKey="entity.action.view">View</Translate>
                        </span>
                      </Button>
                      <Button tag={Link} to={`/skill-atk/${skillATK.id}/edit`} color="primary" size="sm" data-cy="entityEditButton">
                        <FontAwesomeIcon icon="pencil-alt" />{' '}
                        <span className="d-none d-md-inline">
                          <Translate contentKey="entity.action.edit">Edit</Translate>
                        </span>
                      </Button>
                      <Button tag={Link} to={`/skill-atk/${skillATK.id}/delete`} color="danger" size="sm" data-cy="entityDeleteButton">
                        <FontAwesomeIcon icon="trash" />{' '}
                        <span className="d-none d-md-inline">
                          <Translate contentKey="entity.action.delete">Delete</Translate>
                        </span>
                      </Button>
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </Table>
        ) : (
          !loading && (
            <div className="alert alert-warning">
              <Translate contentKey="elementaltakedownApp.skillATK.home.notFound">No Skill ATKS found</Translate>
            </div>
          )
        )}
      </div>
    </div>
  );
};

export default SkillATK;

// elementaltakedown/src/main/webapp/app/entities/skill-atk/list/skill-atk.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute, Data, ParamMap, Router } from '@angular/router';
import { combineLatest, filter, Observable, switchMap, tap } from 'rxjs';
import { NgbModal } from '@ng-bootstrap/ng-bootstrap';

import { ISkillATK } from '../skill-atk.model';
import { ASC, DESC, SORT, ITEM_DELETED_EVENT, DEFAULT_SORT_DATA } from 'app/config/navigation.constants';
import { EntityArrayResponseType, SkillATKService } from '../service/skill-atk.service';
import { SkillATKDeleteDialogComponent } from '../delete/skill-atk-delete-dialog.component';
import { SortService } from 'app/shared/sort/sort.service';

@Component({
  selector: 'jhi-skill-atk',
  templateUrl: './skill-atk.component.html',
})
export class SkillATKComponent implements OnInit {
  skillATKS?: ISkillATK[];
  isLoading = false;

  predicate = 'id';
  ascending = true;

  constructor(
    protected skillATKService: SkillATKService,
    protected activatedRoute: ActivatedRoute,
    public router: Router,
    protected sortService: SortService,
    protected modalService: NgbModal
  ) {}

  trackId = (_index: number, item: ISkillATK): number => this.skillATKService.getSkillATKIdentifier(item);

  ngOnInit(): void {
    this.load();
  }

  delete(skillATK: ISkillATK): void {
    const modalRef = this.modalService.open(SkillATKDeleteDialogComponent, { size: 'lg', backdrop: 'static' });
    modalRef.componentInstance.skillATK = skillATK;
    // unsubscribe not needed because closed completes on modal close
    modalRef.closed
      .pipe(
        filter(reason => reason === ITEM_DELETED_EVENT),
        switchMap(() => this.loadFromBackendWithRouteInformations())
      )
      .subscribe({
        next: (res: EntityArrayResponseType) => {
          this.onResponseSuccess(res);
        },
      });
  }

  load(): void {
    this.loadFromBackendWithRouteInformations().subscribe({
      next: (res: EntityArrayResponseType) => {
        this.onResponseSuccess(res);
      },
    });
  }

  navigateToWithComponentValues(): void {
    this.handleNavigation(this.predicate, this.ascending);
  }

  protected loadFromBackendWithRouteInformations(): Observable<EntityArrayResponseType> {
    return combineLatest([this.activatedRoute.queryParamMap, this.activatedRoute.data]).pipe(
      tap(([params, data]) => this.fillComponentAttributeFromRoute(params, data)),
      switchMap(() => this.queryBackend(this.predicate, this.ascending))
    );
  }

  protected fillComponentAttributeFromRoute(params: ParamMap, data: Data): void {
    const sort = (params.get(SORT) ?? data[DEFAULT_SORT_DATA]).split(',');
    this.predicate = sort[0];
    this.ascending = sort[1] === ASC;
  }

  protected onResponseSuccess(response: EntityArrayResponseType): void {
    const dataFromBody = this.fillComponentAttributesFromResponseBody(response.body);
    this.skillATKS = this.refineData(dataFromBody);
  }

  protected refineData(data: ISkillATK[]): ISkillATK[] {
    return data.sort(this.sortService.startSort(this.predicate, this.ascending ? 1 : -1));
  }

  protected fillComponentAttributesFromResponseBody(data: ISkillATK[] | null): ISkillATK[] {
    return data ?? [];
  }

  protected queryBackend(predicate?: string, ascending?: boolean): Observable<EntityArrayResponseType> {
    this.isLoading = true;
    const queryObject = {
      eagerload: true,
      sort: this.getSortQueryParam(predicate, ascending),
    };
    return this.skillATKService.query(queryObject).pipe(tap(() => (this.isLoading = false)));
  }

  protected handleNavigation(predicate?: string, ascending?: boolean): void {
    const queryParamsObj = {
      sort: this.getSortQueryParam(predicate, ascending),
    };

    this.router.navigate(['./'], {
      relativeTo: this.activatedRoute,
      queryParams: queryParamsObj,
    });
  }

  protected getSortQueryParam(predicate = this.predicate, ascending = this.ascending): string[] {
    const ascendingQueryParam = ascending ? ASC : DESC;
    if (predicate === '') {
      return [];
    } else {
      return [predicate + ',' + ascendingQueryParam];
    }
  }
}

<div>
  <h2 id="page-heading" data-cy="SkillATKHeading">
    <span jhiTranslate="elementaltakedownApp.skillATK.home.title">Skill ATKS</span>

    <div class="d-flex justify-content-end">
      <button class="btn btn-info me-2" (click)="load()" [disabled]="isLoading">
        <fa-icon icon="sync" [spin]="isLoading"></fa-icon>
        <span jhiTranslate="elementaltakedownApp.skillATK.home.refreshListLabel">Refresh list</span>
      </button>

      <button
        id="jh-create-entity"
        data-cy="entityCreateButton"
        class="btn btn-primary jh-create-entity create-skill-atk"
        [routerLink]="['/skill-atk/new']"
      >
        <fa-icon icon="plus"></fa-icon>
        <span jhiTranslate="elementaltakedownApp.skillATK.home.createLabel"> Create a new Skill ATK </span>
      </button>
    </div>
  </h2>

  <jhi-alert-error></jhi-alert-error>

  <jhi-alert></jhi-alert>

  <div class="alert alert-warning" id="no-result" *ngIf="skillATKS?.length === 0">
    <span jhiTranslate="elementaltakedownApp.skillATK.home.notFound">No Skill ATKS found</span>
  </div>

  <div class="table-responsive table-entities" id="entities" *ngIf="skillATKS && skillATKS.length > 0">
    <table class="table table-striped" aria-describedby="page-heading">
      <thead>
        <tr jhiSort [(predicate)]="predicate" [(ascending)]="ascending" (sortChange)="navigateToWithComponentValues()">
          <th scope="col" jhiSortBy="id">
            <div class="d-flex">
              <span jhiTranslate="global.field.id">ID</span>
              <fa-icon class="p-1" icon="sort"></fa-icon>
            </div>
          </th>
          <th scope="col" jhiSortBy="name">
            <div class="d-flex">
              <span jhiTranslate="elementaltakedownApp.skillATK.name">Name</span>
              <fa-icon class="p-1" icon="sort"></fa-icon>
            </div>
          </th>
          <th scope="col" jhiSortBy="description">
            <div class="d-flex">
              <span jhiTranslate="elementaltakedownApp.skillATK.description">Description</span>
              <fa-icon class="p-1" icon="sort"></fa-icon>
            </div>
          </th>
          <th scope="col" jhiSortBy="damage.name">
            <div class="d-flex">
              <span jhiTranslate="elementaltakedownApp.skillATK.damage">Damage</span>
              <fa-icon class="p-1" icon="sort"></fa-icon>
            </div>
          </th>
          <th scope="col"></th>
        </tr>
      </thead>
      <tbody>
        <tr *ngFor="let skillATK of skillATKS; trackBy: trackId" data-cy="entityTable">
          <td>
            <a [routerLink]="['/skill-atk', skillATK.id, 'view']">{{ skillATK.id }}</a>
          </td>
          <td>{{ skillATK.name }}</td>
          <td>{{ skillATK.description }}</td>
          <td>
            <div *ngIf="skillATK.damage">
              <a [routerLink]="['/damage', skillATK.damage.id, 'view']">{{ skillATK.damage.name }}</a>
            </div>
          </td>
          <td class="text-end">
            <div class="btn-group">
              <button
                type="submit"
                [routerLink]="['/skill-atk', skillATK.id, 'view']"
                class="btn btn-info btn-sm"
                data-cy="entityDetailsButton"
              >
                <fa-icon icon="eye"></fa-icon>
                <span class="d-none d-md-inline" jhiTranslate="entity.action.view">View</span>
              </button>

              <button
                type="submit"
                [routerLink]="['/skill-atk', skillATK.id, 'edit']"
                class="btn btn-primary btn-sm"
                data-cy="entityEditButton"
              >
                <fa-icon icon="pencil-alt"></fa-icon>
                <span class="d-none d-md-inline" jhiTranslate="entity.action.edit">Edit</span>
              </button>

              <button type="submit" (click)="delete(skillATK)" class="btn btn-danger btn-sm" data-cy="entityDeleteButton">
                <fa-icon icon="times"></fa-icon>
                <span class="d-none d-md-inline" jhiTranslate="entity.action.delete">Delete</span>
              </button>
            </div>
          </td>
        </tr>
      </tbody>
    </table>
  </div>
</div>
