// elementaltakedown/src/main/webapp/app/entities/character-card/character-card-update.tsx
import React, { useState, useEffect } from 'react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import { Button, Row, Col, FormText } from 'reactstrap';
import { isNumber, Translate, translate, ValidatedField, ValidatedForm } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { convertDateTimeFromServer, convertDateTimeToServer, displayDefaultDateTime } from 'app/shared/util/date-utils';
import { mapIdList } from 'app/shared/util/entity-utils';
import { useAppDispatch, useAppSelector } from 'app/config/store';

import { IBasicATK } from 'app/shared/model/basic-atk.model';
import { getEntities as getBasicAtks } from 'app/entities/basic-atk/basic-atk.reducer';
import { ISkillATK } from 'app/shared/model/skill-atk.model';
import { getEntities as getSkillAtks } from 'app/entities/skill-atk/skill-atk.reducer';
import { IUltimateATK } from 'app/shared/model/ultimate-atk.model';
import { getEntities as getUltimateAtks } from 'app/entities/ultimate-atk/ultimate-atk.reducer';
import { IUserProfile } from 'app/shared/model/user-profile.model';
import { getEntities as getUserProfiles } from 'app/entities/user-profile/user-profile.reducer';
import { ICharacterCard } from 'app/shared/model/character-card.model';
import { ElementType } from 'app/shared/model/enumerations/element-type.model';
import { getEntity, updateEntity, createEntity, reset } from './character-card.reducer';

export const CharacterCardUpdate = () => {
  const dispatch = useAppDispatch();

  const navigate = useNavigate();

  const { id } = useParams<'id'>();
  const isNew = id === undefined;

  const basicATKS = useAppSelector(state => state.basicATK.entities);
  const skillATKS = useAppSelector(state => state.skillATK.entities);
  const ultimateATKS = useAppSelector(state => state.ultimateATK.entities);
  const userProfiles = useAppSelector(state => state.userProfile.entities);
  const characterCardEntity = useAppSelector(state => state.characterCard.entity);
  const loading = useAppSelector(state => state.characterCard.loading);
  const updating = useAppSelector(state => state.characterCard.updating);
  const updateSuccess = useAppSelector(state => state.characterCard.updateSuccess);
  const elementTypeValues = Object.keys(ElementType);

  const handleClose = () => {
    navigate('/character-card');
  };

  useEffect(() => {
    if (isNew) {
      dispatch(reset());
    } else {
      dispatch(getEntity(id));
    }

    dispatch(getBasicAtks({}));
    dispatch(getSkillAtks({}));
    dispatch(getUltimateAtks({}));
    dispatch(getUserProfiles({}));
  }, []);

  useEffect(() => {
    if (updateSuccess) {
      handleClose();
    }
  }, [updateSuccess]);

  const saveEntity = values => {
    const entity = {
      ...characterCardEntity,
      ...values,
      basic: basicATKS.find(it => it.id.toString() === values.basic.toString()),
      skill: skillATKS.find(it => it.id.toString() === values.skill.toString()),
      ultimate: ultimateATKS.find(it => it.id.toString() === values.ultimate.toString()),
    };

    if (isNew) {
      dispatch(createEntity(entity));
    } else {
      dispatch(updateEntity(entity));
    }
  };

  const defaultValues = () =>
    isNew
      ? {}
      : {
          element: 'WATER',
          ...characterCardEntity,
          basic: characterCardEntity?.basic?.id,
          skill: characterCardEntity?.skill?.id,
          ultimate: characterCardEntity?.ultimate?.id,
        };

  return (
    <div>
      <Row className="justify-content-center">
        <Col md="8">
          <h2 id="elementaltakedownApp.characterCard.home.createOrEditLabel" data-cy="CharacterCardCreateUpdateHeading">
            <Translate contentKey="elementaltakedownApp.characterCard.home.createOrEditLabel">Create or edit a CharacterCard</Translate>
          </h2>
        </Col>
      </Row>
      <Row className="justify-content-center">
        <Col md="8">
          {loading ? (
            <p>Loading...</p>
          ) : (
            <ValidatedForm defaultValues={defaultValues()} onSubmit={saveEntity}>
              {!isNew ? (
                <ValidatedField
                  name="id"
                  required
                  readOnly
                  id="character-card-id"
                  label={translate('global.field.id')}
                  validate={{ required: true }}
                />
              ) : null}
              <ValidatedField
                label={translate('elementaltakedownApp.characterCard.name')}
                id="character-card-name"
                name="name"
                data-cy="name"
                type="text"
                validate={{
                  required: { value: true, message: translate('entity.validation.required') },
                }}
              />
              <ValidatedField
                label={translate('elementaltakedownApp.characterCard.element')}
                id="character-card-element"
                name="element"
                data-cy="element"
                type="select"
              >
                {elementTypeValues.map(elementType => (
                  <option value={elementType} key={elementType}>
                    {translate('elementaltakedownApp.ElementType.' + elementType)}
                  </option>
                ))}
              </ValidatedField>
              <ValidatedField
                id="character-card-basic"
                name="basic"
                data-cy="basic"
                label={translate('elementaltakedownApp.characterCard.basic')}
                type="select"
                required
              >
                <option value="" key="0" />
                {basicATKS
                  ? basicATKS.map(otherEntity => (
                      <option value={otherEntity.id} key={otherEntity.id}>
                        {otherEntity.name}
                      </option>
                    ))
                  : null}
              </ValidatedField>
              <FormText>
                <Translate contentKey="entity.validation.required">This field is required.</Translate>
              </FormText>
              <ValidatedField
                id="character-card-skill"
                name="skill"
                data-cy="skill"
                label={translate('elementaltakedownApp.characterCard.skill')}
                type="select"
                required
              >
                <option value="" key="0" />
                {skillATKS
                  ? skillATKS.map(otherEntity => (
                      <option value={otherEntity.id} key={otherEntity.id}>
                        {otherEntity.name}
                      </option>
                    ))
                  : null}
              </ValidatedField>
              <FormText>
                <Translate contentKey="entity.validation.required">This field is required.</Translate>
              </FormText>
              <ValidatedField
                id="character-card-ultimate"
                name="ultimate"
                data-cy="ultimate"
                label={translate('elementaltakedownApp.characterCard.ultimate')}
                type="select"
                required
              >
                <option value="" key="0" />
                {ultimateATKS
                  ? ultimateATKS.map(otherEntity => (
                      <option value={otherEntity.id} key={otherEntity.id}>
                        {otherEntity.name}
                      </option>
                    ))
                  : null}
              </ValidatedField>
              <FormText>
                <Translate contentKey="entity.validation.required">This field is required.</Translate>
              </FormText>
              <Button tag={Link} id="cancel-save" data-cy="entityCreateCancelButton" to="/character-card" replace color="info">
                <FontAwesomeIcon icon="arrow-left" />
                &nbsp;
                <span className="d-none d-md-inline">
                  <Translate contentKey="entity.action.back">Back</Translate>
                </span>
              </Button>
              &nbsp;
              <Button color="primary" id="save-entity" data-cy="entityCreateSaveButton" type="submit" disabled={updating}>
                <FontAwesomeIcon icon="save" />
                &nbsp;
                <Translate contentKey="entity.action.save">Save</Translate>
              </Button>
            </ValidatedForm>
          )}
        </Col>
      </Row>
    </div>
  );
};

export default CharacterCardUpdate;

// elementaltakedown/src/main/webapp/app/entities/character-card/update/character-card-update.component.ts
import { Component, OnInit } from '@angular/core';
import { HttpResponse } from '@angular/common/http';
import { ActivatedRoute } from '@angular/router';
import { Observable } from 'rxjs';
import { finalize, map } from 'rxjs/operators';

import { CharacterCardFormService, CharacterCardFormGroup } from './character-card-form.service';
import { ICharacterCard } from '../character-card.model';
import { CharacterCardService } from '../service/character-card.service';
import { IBasicATK } from 'app/entities/basic-atk/basic-atk.model';
import { BasicATKService } from 'app/entities/basic-atk/service/basic-atk.service';
import { ISkillATK } from 'app/entities/skill-atk/skill-atk.model';
import { SkillATKService } from 'app/entities/skill-atk/service/skill-atk.service';
import { IUltimateATK } from 'app/entities/ultimate-atk/ultimate-atk.model';
import { UltimateATKService } from 'app/entities/ultimate-atk/service/ultimate-atk.service';
import { ElementType } from 'app/entities/enumerations/element-type.model';

@Component({
  selector: 'jhi-character-card-update',
  templateUrl: './character-card-update.component.html',
})
export class CharacterCardUpdateComponent implements OnInit {
  isSaving = false;
  characterCard: ICharacterCard | null = null;
  elementTypeValues = Object.keys(ElementType);

  basicATKSSharedCollection: IBasicATK[] = [];
  skillATKSSharedCollection: ISkillATK[] = [];
  ultimateATKSSharedCollection: IUltimateATK[] = [];

  editForm: CharacterCardFormGroup = this.characterCardFormService.createCharacterCardFormGroup();

  constructor(
    protected characterCardService: CharacterCardService,
    protected characterCardFormService: CharacterCardFormService,
    protected basicATKService: BasicATKService,
    protected skillATKService: SkillATKService,
    protected ultimateATKService: UltimateATKService,
    protected activatedRoute: ActivatedRoute
  ) {}

  compareBasicATK = (o1: IBasicATK | null, o2: IBasicATK | null): boolean => this.basicATKService.compareBasicATK(o1, o2);

  compareSkillATK = (o1: ISkillATK | null, o2: ISkillATK | null): boolean => this.skillATKService.compareSkillATK(o1, o2);

  compareUltimateATK = (o1: IUltimateATK | null, o2: IUltimateATK | null): boolean => this.ultimateATKService.compareUltimateATK(o1, o2);

  ngOnInit(): void {
    this.activatedRoute.data.subscribe(({ characterCard }) => {
      this.characterCard = characterCard;
      if (characterCard) {
        this.updateForm(characterCard);
      }

      this.loadRelationshipsOptions();
    });
  }

  previousState(): void {
    window.history.back();
  }

  save(): void {
    this.isSaving = true;
    const characterCard = this.characterCardFormService.getCharacterCard(this.editForm);
    if (characterCard.id !== null) {
      this.subscribeToSaveResponse(this.characterCardService.update(characterCard));
    } else {
      this.subscribeToSaveResponse(this.characterCardService.create(characterCard));
    }
  }

  protected subscribeToSaveResponse(result: Observable<HttpResponse<ICharacterCard>>): void {
    result.pipe(finalize(() => this.onSaveFinalize())).subscribe({
      next: () => this.onSaveSuccess(),
      error: () => this.onSaveError(),
    });
  }

  protected onSaveSuccess(): void {
    this.previousState();
  }

  protected onSaveError(): void {
    // Api for inheritance.
  }

  protected onSaveFinalize(): void {
    this.isSaving = false;
  }

  protected updateForm(characterCard: ICharacterCard): void {
    this.characterCard = characterCard;
    this.characterCardFormService.resetForm(this.editForm, characterCard);

    this.basicATKSSharedCollection = this.basicATKService.addBasicATKToCollectionIfMissing<IBasicATK>(
      this.basicATKSSharedCollection,
      characterCard.basic
    );
    this.skillATKSSharedCollection = this.skillATKService.addSkillATKToCollectionIfMissing<ISkillATK>(
      this.skillATKSSharedCollection,
      characterCard.skill
    );
    this.ultimateATKSSharedCollection = this.ultimateATKService.addUltimateATKToCollectionIfMissing<IUltimateATK>(
      this.ultimateATKSSharedCollection,
      characterCard.ultimate
    );
  }

  protected loadRelationshipsOptions(): void {
    this.basicATKService
      .query()
      .pipe(map((res: HttpResponse<IBasicATK[]>) => res.body ?? []))
      .pipe(
        map((basicATKS: IBasicATK[]) =>
          this.basicATKService.addBasicATKToCollectionIfMissing<IBasicATK>(basicATKS, this.characterCard?.basic)
        )
      )
      .subscribe((basicATKS: IBasicATK[]) => (this.basicATKSSharedCollection = basicATKS));

    this.skillATKService
      .query()
      .pipe(map((res: HttpResponse<ISkillATK[]>) => res.body ?? []))
      .pipe(
        map((skillATKS: ISkillATK[]) =>
          this.skillATKService.addSkillATKToCollectionIfMissing<ISkillATK>(skillATKS, this.characterCard?.skill)
        )
      )
      .subscribe((skillATKS: ISkillATK[]) => (this.skillATKSSharedCollection = skillATKS));

    this.ultimateATKService
      .query()
      .pipe(map((res: HttpResponse<IUltimateATK[]>) => res.body ?? []))
      .pipe(
        map((ultimateATKS: IUltimateATK[]) =>
          this.ultimateATKService.addUltimateATKToCollectionIfMissing<IUltimateATK>(ultimateATKS, this.characterCard?.ultimate)
        )
      )
      .subscribe((ultimateATKS: IUltimateATK[]) => (this.ultimateATKSSharedCollection = ultimateATKS));
  }
}

<div class="d-flex justify-content-center">
  <div class="col-8">
    <form name="editForm" role="form" novalidate (ngSubmit)="save()" [formGroup]="editForm">
      <h2
        id="jhi-character-card-heading"
        data-cy="CharacterCardCreateUpdateHeading"
        jhiTranslate="elementaltakedownApp.characterCard.home.createOrEditLabel"
      >
        Create or edit a Character Card
      </h2>

      <div>
        <jhi-alert-error></jhi-alert-error>

        <div class="row mb-3" *ngIf="editForm.controls.id.value !== null">
          <label class="form-label" jhiTranslate="global.field.id" for="field_id">ID</label>
          <input type="number" class="form-control" name="id" id="field_id" data-cy="id" formControlName="id" [readonly]="true" />
        </div>

        <div class="row mb-3">
          <label class="form-label" jhiTranslate="elementaltakedownApp.characterCard.name" for="field_name">Name</label>
          <input type="text" class="form-control" name="name" id="field_name" data-cy="name" formControlName="name" />
          <div *ngIf="editForm.get('name')!.invalid && (editForm.get('name')!.dirty || editForm.get('name')!.touched)">
            <small class="form-text text-danger" *ngIf="editForm.get('name')?.errors?.required" jhiTranslate="entity.validation.required">
              This field is required.
            </small>
          </div>
        </div>

        <div class="row mb-3">
          <label class="form-label" jhiTranslate="elementaltakedownApp.characterCard.element" for="field_element">Element</label>
          <select class="form-control" name="element" formControlName="element" id="field_element" data-cy="element">
            <option [ngValue]="null">{{ 'elementaltakedownApp.ElementType.null' | translate }}</option>
            <option *ngFor="let elementType of elementTypeValues" [value]="elementType">
              {{ 'elementaltakedownApp.ElementType.' + elementType | translate }}
            </option>
          </select>
          <div *ngIf="editForm.get('element')!.invalid && (editForm.get('element')!.dirty || editForm.get('element')!.touched)">
            <small
              class="form-text text-danger"
              *ngIf="editForm.get('element')?.errors?.required"
              jhiTranslate="entity.validation.required"
            >
              This field is required.
            </small>
          </div>
        </div>

        <div class="row mb-3">
          <label class="form-label" jhiTranslate="elementaltakedownApp.characterCard.basic" for="field_basic">Basic</label>
          <select
            class="form-control"
            id="field_basic"
            data-cy="basic"
            name="basic"
            formControlName="basic"
            [compareWith]="compareBasicATK"
          >
            <option *ngIf="!editForm.get('basic')!.value" [ngValue]="null" selected></option>
            <option [ngValue]="basicATKOption" *ngFor="let basicATKOption of basicATKSSharedCollection">{{ basicATKOption.name }}</option>
          </select>
        </div>
        <div *ngIf="editForm.get(['basic'])!.invalid && (editForm.get(['basic'])!.dirty || editForm.get(['basic'])!.touched)">
          <small class="form-text text-danger" *ngIf="editForm.get(['basic'])?.errors?.required" jhiTranslate="entity.validation.required">
            This field is required.
          </small>
        </div>

        <div class="row mb-3">
          <label class="form-label" jhiTranslate="elementaltakedownApp.characterCard.skill" for="field_skill">Skill</label>
          <select
            class="form-control"
            id="field_skill"
            data-cy="skill"
            name="skill"
            formControlName="skill"
            [compareWith]="compareSkillATK"
          >
            <option *ngIf="!editForm.get('skill')!.value" [ngValue]="null" selected></option>
            <option [ngValue]="skillATKOption" *ngFor="let skillATKOption of skillATKSSharedCollection">{{ skillATKOption.name }}</option>
          </select>
        </div>
        <div *ngIf="editForm.get(['skill'])!.invalid && (editForm.get(['skill'])!.dirty || editForm.get(['skill'])!.touched)">
          <small class="form-text text-danger" *ngIf="editForm.get(['skill'])?.errors?.required" jhiTranslate="entity.validation.required">
            This field is required.
          </small>
        </div>

        <div class="row mb-3">
          <label class="form-label" jhiTranslate="elementaltakedownApp.characterCard.ultimate" for="field_ultimate">Ultimate</label>
          <select
            class="form-control"
            id="field_ultimate"
            data-cy="ultimate"
            name="ultimate"
            formControlName="ultimate"
            [compareWith]="compareUltimateATK"
          >
            <option *ngIf="!editForm.get('ultimate')!.value" [ngValue]="null" selected></option>
            <option [ngValue]="ultimateATKOption" *ngFor="let ultimateATKOption of ultimateATKSSharedCollection">
              {{ ultimateATKOption.name }}
            </option>
          </select>
        </div>
        <div *ngIf="editForm.get(['ultimate'])!.invalid && (editForm.get(['ultimate'])!.dirty || editForm.get(['ultimate'])!.touched)">
          <small
            class="form-text text-danger"
            *ngIf="editForm.get(['ultimate'])?.errors?.required"
            jhiTranslate="entity.validation.required"
          >
            This field is required.
          </small>
        </div>
      </div>

      <div>
        <button type="button" id="cancel-save" data-cy="entityCreateCancelButton" class="btn btn-secondary" (click)="previousState()">
          <fa-icon icon="ban"></fa-icon>&nbsp;<span jhiTranslate="entity.action.cancel">Cancel</span>
        </button>

        <button
          type="submit"
          id="save-entity"
          data-cy="entityCreateSaveButton"
          [disabled]="editForm.invalid || isSaving"
          class="btn btn-primary"
        >
          <fa-icon icon="save"></fa-icon>&nbsp;<span jhiTranslate="entity.action.save">Save</span>
        </button>
      </div>
    </form>
  </div>
</div>
