// elementaltakedown/src/main/webapp/app/entities/damage/list/damage.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute, Data, ParamMap, Router } from '@angular/router';
import { combineLatest, filter, Observable, switchMap, tap } from 'rxjs';
import { NgbModal } from '@ng-bootstrap/ng-bootstrap';

import { IDamage } from '../damage.model';
import { ASC, DESC, SORT, ITEM_DELETED_EVENT, DEFAULT_SORT_DATA } from 'app/config/navigation.constants';
import { EntityArrayResponseType, DamageService } from '../service/damage.service';
import { DamageDeleteDialogComponent } from '../delete/damage-delete-dialog.component';
import { SortService } from 'app/shared/sort/sort.service';

@Component({
  selector: 'jhi-damage',
  templateUrl: './damage.component.html',
})
export class DamageComponent implements OnInit {
  damages?: IDamage[];
  isLoading = false;

  predicate = 'id';
  ascending = true;

  constructor(
    protected damageService: DamageService,
    protected activatedRoute: ActivatedRoute,
    public router: Router,
    protected sortService: SortService,
    protected modalService: NgbModal
  ) {}

  trackId = (_index: number, item: IDamage): number => this.damageService.getDamageIdentifier(item);

  ngOnInit(): void {
    this.load();
  }

  delete(damage: IDamage): void {
    const modalRef = this.modalService.open(DamageDeleteDialogComponent, { size: 'lg', backdrop: 'static' });
    modalRef.componentInstance.damage = damage;
    // unsubscribe not needed because closed completes on modal close
    modalRef.closed
      .pipe(
        filter(reason => reason === ITEM_DELETED_EVENT),
        switchMap(() => this.loadFromBackendWithRouteInformations())
      )
      .subscribe({
        next: (res: EntityArrayResponseType) => {
          this.onResponseSuccess(res);
        },
      });
  }

  load(): void {
    this.loadFromBackendWithRouteInformations().subscribe({
      next: (res: EntityArrayResponseType) => {
        this.onResponseSuccess(res);
      },
    });
  }

  navigateToWithComponentValues(): void {
    this.handleNavigation(this.predicate, this.ascending);
  }

  protected loadFromBackendWithRouteInformations(): Observable<EntityArrayResponseType> {
    return combineLatest([this.activatedRoute.queryParamMap, this.activatedRoute.data]).pipe(
      tap(([params, data]) => this.fillComponentAttributeFromRoute(params, data)),
      switchMap(() => this.queryBackend(this.predicate, this.ascending))
    );
  }

  protected fillComponentAttributeFromRoute(params: ParamMap, data: Data): void {
    const sort = (params.get(SORT) ?? data[DEFAULT_SORT_DATA]).split(',');
    this.predicate = sort[0];
    this.ascending = sort[1] === ASC;
  }

  protected onResponseSuccess(response: EntityArrayResponseType): void {
    const dataFromBody = this.fillComponentAttributesFromResponseBody(response.body);
    this.damages = this.refineData(dataFromBody);
  }

  protected refineData(data: IDamage[]): IDamage[] {
    return data.sort(this.sortService.startSort(this.predicate, this.ascending ? 1 : -1));
  }

  protected fillComponentAttributesFromResponseBody(data: IDamage[] | null): IDamage[] {
    return data ?? [];
  }

  protected queryBackend(predicate?: string, ascending?: boolean): Observable<EntityArrayResponseType> {
    this.isLoading = true;
    const queryObject = {
      sort: this.getSortQueryParam(predicate, ascending),
    };
    return this.damageService.query(queryObject).pipe(tap(() => (this.isLoading = false)));
  }

  protected handleNavigation(predicate?: string, ascending?: boolean): void {
    const queryParamsObj = {
      sort: this.getSortQueryParam(predicate, ascending),
    };

    this.router.navigate(['./'], {
      relativeTo: this.activatedRoute,
      queryParams: queryParamsObj,
    });
  }

  protected getSortQueryParam(predicate = this.predicate, ascending = this.ascending): string[] {
    const ascendingQueryParam = ascending ? ASC : DESC;
    if (predicate === '') {
      return [];
    } else {
      return [predicate + ',' + ascendingQueryParam];
    }
  }
}

<div>
  <h2 id="page-heading" data-cy="DamageHeading">
    <span jhiTranslate="elementaltakedownApp.damage.home.title">Damages</span>

    <div class="d-flex justify-content-end">
      <button class="btn btn-info me-2" (click)="load()" [disabled]="isLoading">
        <fa-icon icon="sync" [spin]="isLoading"></fa-icon>
        <span jhiTranslate="elementaltakedownApp.damage.home.refreshListLabel">Refresh list</span>
      </button>

      <button
        id="jh-create-entity"
        data-cy="entityCreateButton"
        class="btn btn-primary jh-create-entity create-damage"
        [routerLink]="['/damage/new']"
      >
        <fa-icon icon="plus"></fa-icon>
        <span jhiTranslate="elementaltakedownApp.damage.home.createLabel"> Create a new Damage </span>
      </button>
    </div>
  </h2>

  <jhi-alert-error></jhi-alert-error>

  <jhi-alert></jhi-alert>

  <div class="alert alert-warning" id="no-result" *ngIf="damages?.length === 0">
    <span jhiTranslate="elementaltakedownApp.damage.home.notFound">No Damages found</span>
  </div>

  <div class="table-responsive table-entities" id="entities" *ngIf="damages && damages.length > 0">
    <table class="table table-striped" aria-describedby="page-heading">
      <thead>
        <tr jhiSort [(predicate)]="predicate" [(ascending)]="ascending" (sortChange)="navigateToWithComponentValues()">
          <th scope="col" jhiSortBy="id">
            <div class="d-flex">
              <span jhiTranslate="global.field.id">ID</span>
              <fa-icon class="p-1" icon="sort"></fa-icon>
            </div>
          </th>
          <th scope="col" jhiSortBy="name">
            <div class="d-flex">
              <span jhiTranslate="elementaltakedownApp.damage.name">Name</span>
              <fa-icon class="p-1" icon="sort"></fa-icon>
            </div>
          </th>
          <th scope="col" jhiSortBy="dmgValue">
            <div class="d-flex">
              <span jhiTranslate="elementaltakedownApp.damage.dmgValue">Dmg Value</span>
              <fa-icon class="p-1" icon="sort"></fa-icon>
            </div>
          </th>
          <th scope="col" jhiSortBy="dmgElement">
            <div class="d-flex">
              <span jhiTranslate="elementaltakedownApp.damage.dmgElement">Dmg Element</span>
              <fa-icon class="p-1" icon="sort"></fa-icon>
            </div>
          </th>
          <th scope="col"></th>
        </tr>
      </thead>
      <tbody>
        <tr *ngFor="let damage of damages; trackBy: trackId" data-cy="entityTable">
          <td>
            <a [routerLink]="['/damage', damage.id, 'view']">{{ damage.id }}</a>
          </td>
          <td>{{ damage.name }}</td>
          <td>{{ damage.dmgValue }}</td>
          <td jhiTranslate="{{ 'elementaltakedownApp.DmgElementType.' + damage.dmgElement }}">{{ damage.dmgElement }}</td>
          <td class="text-end">
            <div class="btn-group">
              <button type="submit" [routerLink]="['/damage', damage.id, 'view']" class="btn btn-info btn-sm" data-cy="entityDetailsButton">
                <fa-icon icon="eye"></fa-icon>
                <span class="d-none d-md-inline" jhiTranslate="entity.action.view">View</span>
              </button>

              <button type="submit" [routerLink]="['/damage', damage.id, 'edit']" class="btn btn-primary btn-sm" data-cy="entityEditButton">
                <fa-icon icon="pencil-alt"></fa-icon>
                <span class="d-none d-md-inline" jhiTranslate="entity.action.edit">Edit</span>
              </button>

              <button type="submit" (click)="delete(damage)" class="btn btn-danger btn-sm" data-cy="entityDeleteButton">
                <fa-icon icon="times"></fa-icon>
                <span class="d-none d-md-inline" jhiTranslate="entity.action.delete">Delete</span>
              </button>
            </div>
          </td>
        </tr>
      </tbody>
    </table>
  </div>
</div>

// elementaltakedown/src/main/webapp/app/entities/damage/damage.tsx
import React, { useState, useEffect } from 'react';
import { Link, useLocation, useNavigate } from 'react-router-dom';
import { Button, Table } from 'reactstrap';
import { Translate } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { APP_DATE_FORMAT, APP_LOCAL_DATE_FORMAT } from 'app/config/constants';
import { useAppDispatch, useAppSelector } from 'app/config/store';

import { IDamage } from 'app/shared/model/damage.model';
import { getEntities } from './damage.reducer';

export const Damage = () => {
  const dispatch = useAppDispatch();

  const location = useLocation();
  const navigate = useNavigate();

  const damageList = useAppSelector(state => state.damage.entities);
  const loading = useAppSelector(state => state.damage.loading);

  useEffect(() => {
    dispatch(getEntities({}));
  }, []);

  const handleSyncList = () => {
    dispatch(getEntities({}));
  };

  return (
    <div>
      <h2 id="damage-heading" data-cy="DamageHeading">
        <Translate contentKey="elementaltakedownApp.damage.home.title">Damages</Translate>
        <div className="d-flex justify-content-end">
          <Button className="me-2" color="info" onClick={handleSyncList} disabled={loading}>
            <FontAwesomeIcon icon="sync" spin={loading} />{' '}
            <Translate contentKey="elementaltakedownApp.damage.home.refreshListLabel">Refresh List</Translate>
          </Button>
          <Link to="/damage/new" className="btn btn-primary jh-create-entity" id="jh-create-entity" data-cy="entityCreateButton">
            <FontAwesomeIcon icon="plus" />
            &nbsp;
            <Translate contentKey="elementaltakedownApp.damage.home.createLabel">Create new Damage</Translate>
          </Link>
        </div>
      </h2>
      <div className="table-responsive">
        {damageList && damageList.length > 0 ? (
          <Table responsive>
            <thead>
              <tr>
                <th>
                  <Translate contentKey="elementaltakedownApp.damage.id">ID</Translate>
                </th>
                <th>
                  <Translate contentKey="elementaltakedownApp.damage.name">Name</Translate>
                </th>
                <th>
                  <Translate contentKey="elementaltakedownApp.damage.dmgValue">Dmg Value</Translate>
                </th>
                <th>
                  <Translate contentKey="elementaltakedownApp.damage.dmgElement">Dmg Element</Translate>
                </th>
                <th>
                  <Translate contentKey="elementaltakedownApp.damage.splashDmg">Splash Dmg</Translate>
                </th>
                <th>
                  <Translate contentKey="elementaltakedownApp.damage.splashElement">Splash Element</Translate>
                </th>
                <th />
              </tr>
            </thead>
            <tbody>
              {damageList.map((damage, i) => (
                <tr key={`entity-${i}`} data-cy="entityTable">
                  <td>
                    <Button tag={Link} to={`/damage/${damage.id}`} color="link" size="sm">
                      {damage.id}
                    </Button>
                  </td>
                  <td>{damage.name}</td>
                  <td>{damage.dmgValue}</td>
                  <td>
                    <Translate contentKey={`elementaltakedownApp.DmgElementType.${damage.dmgElement}`} />
                  </td>
                  <td>{damage.splashDmg}</td>
                  <td>
                    <Translate contentKey={`elementaltakedownApp.DmgElementType.${damage.splashElement}`} />
                  </td>
                  <td className="text-end">
                    <div className="btn-group flex-btn-group-container">
                      <Button tag={Link} to={`/damage/${damage.id}`} color="info" size="sm" data-cy="entityDetailsButton">
                        <FontAwesomeIcon icon="eye" />{' '}
                        <span className="d-none d-md-inline">
                          <Translate contentKey="entity.action.view">View</Translate>
                        </span>
                      </Button>
                      <Button tag={Link} to={`/damage/${damage.id}/edit`} color="primary" size="sm" data-cy="entityEditButton">
                        <FontAwesomeIcon icon="pencil-alt" />{' '}
                        <span className="d-none d-md-inline">
                          <Translate contentKey="entity.action.edit">Edit</Translate>
                        </span>
                      </Button>
                      <Button tag={Link} to={`/damage/${damage.id}/delete`} color="danger" size="sm" data-cy="entityDeleteButton">
                        <FontAwesomeIcon icon="trash" />{' '}
                        <span className="d-none d-md-inline">
                          <Translate contentKey="entity.action.delete">Delete</Translate>
                        </span>
                      </Button>
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </Table>
        ) : (
          !loading && (
            <div className="alert alert-warning">
              <Translate contentKey="elementaltakedownApp.damage.home.notFound">No Damages found</Translate>
            </div>
          )
        )}
      </div>
    </div>
  );
};

export default Damage;
