// elementaltakedown/src/main/webapp/app/entities/ultimate-atk/ultimate-atk-delete-dialog.tsx
import React, { useEffect, useState } from 'react';
import { useLocation, useNavigate, useParams } from 'react-router-dom';
import { Modal, ModalHeader, ModalBody, ModalFooter, Button } from 'reactstrap';
import { Translate } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { useAppDispatch, useAppSelector } from 'app/config/store';
import { getEntity, deleteEntity } from './ultimate-atk.reducer';

export const UltimateATKDeleteDialog = () => {
  const dispatch = useAppDispatch();

  const location = useLocation();
  const navigate = useNavigate();
  const { id } = useParams<'id'>();

  const [loadModal, setLoadModal] = useState(false);

  useEffect(() => {
    dispatch(getEntity(id));
    setLoadModal(true);
  }, []);

  const ultimateATKEntity = useAppSelector(state => state.ultimateATK.entity);
  const updateSuccess = useAppSelector(state => state.ultimateATK.updateSuccess);

  const handleClose = () => {
    navigate('/ultimate-atk');
  };

  useEffect(() => {
    if (updateSuccess && loadModal) {
      handleClose();
      setLoadModal(false);
    }
  }, [updateSuccess]);

  const confirmDelete = () => {
    dispatch(deleteEntity(ultimateATKEntity.id));
  };

  return (
    <Modal isOpen toggle={handleClose}>
      <ModalHeader toggle={handleClose} data-cy="ultimateATKDeleteDialogHeading">
        <Translate contentKey="entity.delete.title">Confirm delete operation</Translate>
      </ModalHeader>
      <ModalBody id="elementaltakedownApp.ultimateATK.delete.question">
        <Translate contentKey="elementaltakedownApp.ultimateATK.delete.question" interpolate={{ id: ultimateATKEntity.id }}>
          Are you sure you want to delete this UltimateATK?
        </Translate>
      </ModalBody>
      <ModalFooter>
        <Button color="secondary" onClick={handleClose}>
          <FontAwesomeIcon icon="ban" />
          &nbsp;
          <Translate contentKey="entity.action.cancel">Cancel</Translate>
        </Button>
        <Button id="jhi-confirm-delete-ultimateATK" data-cy="entityConfirmDeleteButton" color="danger" onClick={confirmDelete}>
          <FontAwesomeIcon icon="trash" />
          &nbsp;
          <Translate contentKey="entity.action.delete">Delete</Translate>
        </Button>
      </ModalFooter>
    </Modal>
  );
};

export default UltimateATKDeleteDialog;

// elementaltakedown/src/main/webapp/app/entities/ultimate-atk/delete/ultimate-atk-delete-dialog.component.ts
import { Component } from '@angular/core';
import { NgbActiveModal } from '@ng-bootstrap/ng-bootstrap';

import { IUltimateATK } from '../ultimate-atk.model';
import { UltimateATKService } from '../service/ultimate-atk.service';
import { ITEM_DELETED_EVENT } from 'app/config/navigation.constants';

@Component({
  templateUrl: './ultimate-atk-delete-dialog.component.html',
})
export class UltimateATKDeleteDialogComponent {
  ultimateATK?: IUltimateATK;

  constructor(protected ultimateATKService: UltimateATKService, protected activeModal: NgbActiveModal) {}

  cancel(): void {
    this.activeModal.dismiss();
  }

  confirmDelete(id: number): void {
    this.ultimateATKService.delete(id).subscribe(() => {
      this.activeModal.close(ITEM_DELETED_EVENT);
    });
  }
}

<form *ngIf="ultimateATK" name="deleteForm" (ngSubmit)="confirmDelete(ultimateATK.id!)">
  <div class="modal-header">
    <h4 class="modal-title" data-cy="ultimateATKDeleteDialogHeading" jhiTranslate="entity.delete.title">Confirm delete operation</h4>

    <button type="button" class="btn-close" data-dismiss="modal" aria-hidden="true" (click)="cancel()">&times;</button>
  </div>

  <div class="modal-body">
    <jhi-alert-error></jhi-alert-error>
    <p
      id="jhi-delete-ultimateATK-heading"
      jhiTranslate="elementaltakedownApp.ultimateATK.delete.question"
      [translateValues]="{ id: ultimateATK.id }"
    >
      Are you sure you want to delete Ultimate ATK {{ ultimateATK.id }}?
    </p>
  </div>

  <div class="modal-footer">
    <button type="button" class="btn btn-secondary" data-dismiss="modal" (click)="cancel()">
      <fa-icon icon="ban"></fa-icon>&nbsp;<span jhiTranslate="entity.action.cancel">Cancel</span>
    </button>

    <button id="jhi-confirm-delete-ultimateATK" data-cy="entityConfirmDeleteButton" type="submit" class="btn btn-danger">
      <fa-icon icon="times"></fa-icon>&nbsp;<span jhiTranslate="entity.action.delete">Delete</span>
    </button>
  </div>
</form>
